#nullable enable

using System.Text;

namespace Moongazing.OrionGuard.Generators.StronglyTypedIds
{
    internal static class EfCoreConverterEmitter
    {
        public static string Emit(string? @namespace, string typeName, SupportedValueType valueType)
        {
            var valueCsKeyword = SupportedValueTypeMap.CSharpKeyword(valueType);
            var converterName = typeName + "EfCoreValueConverter";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            StronglyTypedIdEmitter.OpenNamespace(sb, @namespace);
            sb.Append("    public sealed class ").Append(converterName)
              .Append(" : global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<")
              .Append(typeName).Append(", ").Append(valueCsKeyword).AppendLine(">");
            sb.AppendLine("    {");
            sb.Append("        public ").Append(converterName).AppendLine("()");
            sb.AppendLine("            : base(id => id.Value, value => new " + typeName + "(value)) { }");
            sb.AppendLine("    }");
            StronglyTypedIdEmitter.CloseNamespace(sb, @namespace);
            return sb.ToString();
        }

        public static string HintName(string hintName) => hintName + "EfCoreValueConverter.g.cs";
    }
}
