#nullable enable

using System.Text;

namespace Moongazing.OrionGuard.Generators.StronglyTypedIds
{
    internal static class JsonConverterEmitter
    {
        public static string Emit(string? @namespace, string typeName, SupportedValueType valueType)
        {
            var (readMethod, writeMethod, valueCsKeyword) = valueType switch
            {
                SupportedValueType.Guid => ("reader.GetGuid()", "WriteStringValue(value.Value)", "global::System.Guid"),
                SupportedValueType.Int32 => ("reader.GetInt32()", "WriteNumberValue(value.Value)", "int"),
                SupportedValueType.Int64 => ("reader.GetInt64()", "WriteNumberValue(value.Value)", "long"),
                SupportedValueType.String => ("reader.GetString() ?? string.Empty", "WriteStringValue(value.Value)", "string"),
                SupportedValueType.Ulid => ("global::System.Ulid.Parse(reader.GetString() ?? string.Empty)", "WriteStringValue(value.Value.ToString())", "global::System.Ulid"),
                _ => ("default", "WriteNullValue()", "object")
            };

            var converterName = typeName + "JsonConverter";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            StronglyTypedIdEmitter.OpenNamespace(sb, @namespace);
            sb.Append("    public sealed class ").Append(converterName)
              .Append(" : global::System.Text.Json.Serialization.JsonConverter<")
              .Append(@namespace is null ? typeName : @namespace + "." + typeName).AppendLine(">");
            sb.AppendLine("    {");
            sb.Append("        public override ").Append(typeName).AppendLine(" Read(");
            sb.AppendLine("            ref global::System.Text.Json.Utf8JsonReader reader,");
            sb.AppendLine("            global::System.Type typeToConvert,");
            sb.AppendLine("            global::System.Text.Json.JsonSerializerOptions options)");
            sb.AppendLine("        {");
            sb.Append("            return new ").Append(typeName).Append("(").Append(readMethod).AppendLine(");");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public override void Write(");
            sb.AppendLine("            global::System.Text.Json.Utf8JsonWriter writer,");
            sb.Append("            ").Append(typeName).AppendLine(" value,");
            sb.AppendLine("            global::System.Text.Json.JsonSerializerOptions options)");
            sb.AppendLine("        {");
            sb.Append("            writer.").Append(writeMethod).AppendLine(";");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            StronglyTypedIdEmitter.CloseNamespace(sb, @namespace);
            return sb.ToString();
        }

        public static string HintName(string hintName) => hintName + "JsonConverter.g.cs";
    }
}
