#nullable enable

using System.Text;

namespace Moongazing.OrionGuard.Generators.StronglyTypedIds
{
    /// <summary>
    /// Emits the <c>IParsable&lt;TSelf&gt;</c> and <c>ISpanParsable&lt;TSelf&gt;</c> implementations
    /// into a secondary partial struct file, so the generated strongly-typed id plays nicely with
    /// ASP.NET Core minimal API parameter binding and other framework parseable consumers.
    /// </summary>
    internal static class ParsableEmitter
    {
        public static string HintName(string typeName) => typeName + ".Parsable.g.cs";

        public static string Emit(string @namespace, string typeName, SupportedValueType valueType)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.Append("namespace ").AppendLine(@namespace);
            sb.AppendLine("{");
            sb.Append("    public readonly partial struct ").Append(typeName)
              .Append(" : global::System.IParsable<").Append(typeName).Append(">")
              .Append(", global::System.ISpanParsable<").Append(typeName).AppendLine(">")
              .AppendLine("    {");

            EmitParseString(sb, typeName, valueType);
            sb.AppendLine();
            EmitTryParseString(sb, typeName, valueType);
            sb.AppendLine();
            EmitParseSpan(sb, typeName, valueType);
            sb.AppendLine();
            EmitTryParseSpan(sb, typeName, valueType);

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void EmitParseString(StringBuilder sb, string typeName, SupportedValueType valueType)
        {
            sb.Append("        public static ").Append(typeName).AppendLine(" Parse(string s, global::System.IFormatProvider? provider)");
            sb.AppendLine("        {");
            switch (valueType)
            {
                case SupportedValueType.Guid:
                    sb.Append("            return new ").Append(typeName).AppendLine("(global::System.Guid.Parse(s, provider));");
                    break;
                case SupportedValueType.Int32:
                    sb.Append("            return new ").Append(typeName).AppendLine("(int.Parse(s, global::System.Globalization.NumberStyles.Integer, provider));");
                    break;
                case SupportedValueType.Int64:
                    sb.Append("            return new ").Append(typeName).AppendLine("(long.Parse(s, global::System.Globalization.NumberStyles.Integer, provider));");
                    break;
                case SupportedValueType.String:
                    sb.AppendLine("            if (s is null) throw new global::System.ArgumentNullException(nameof(s));");
                    sb.Append("            return new ").Append(typeName).AppendLine("(s);");
                    break;
                case SupportedValueType.Ulid:
                    sb.AppendLine("#if NET9_0_OR_GREATER");
                    sb.Append("            return new ").Append(typeName).AppendLine("(global::System.Ulid.Parse(s, provider));");
                    sb.AppendLine("#else");
                    sb.AppendLine("            throw new global::System.PlatformNotSupportedException(\"Ulid requires .NET 9 or later.\");");
                    sb.AppendLine("#endif");
                    break;
            }
            sb.AppendLine("        }");
        }

        private static void EmitTryParseString(StringBuilder sb, string typeName, SupportedValueType valueType)
        {
            sb.Append("        public static bool TryParse(string? s, global::System.IFormatProvider? provider, out ").Append(typeName).AppendLine(" result)");
            sb.AppendLine("        {");
            switch (valueType)
            {
                case SupportedValueType.Guid:
                    sb.AppendLine("            if (global::System.Guid.TryParse(s, provider, out var v)) { result = new " + typeName + "(v); return true; }");
                    sb.AppendLine("            result = default; return false;");
                    break;
                case SupportedValueType.Int32:
                    sb.AppendLine("            if (int.TryParse(s, global::System.Globalization.NumberStyles.Integer, provider, out var v)) { result = new " + typeName + "(v); return true; }");
                    sb.AppendLine("            result = default; return false;");
                    break;
                case SupportedValueType.Int64:
                    sb.AppendLine("            if (long.TryParse(s, global::System.Globalization.NumberStyles.Integer, provider, out var v)) { result = new " + typeName + "(v); return true; }");
                    sb.AppendLine("            result = default; return false;");
                    break;
                case SupportedValueType.String:
                    sb.AppendLine("            if (s is null) { result = default; return false; }");
                    sb.Append("            result = new ").Append(typeName).AppendLine("(s); return true;");
                    break;
                case SupportedValueType.Ulid:
                    sb.AppendLine("#if NET9_0_OR_GREATER");
                    sb.AppendLine("            if (global::System.Ulid.TryParse(s, provider, out var v)) { result = new " + typeName + "(v); return true; }");
                    sb.AppendLine("            result = default; return false;");
                    sb.AppendLine("#else");
                    sb.AppendLine("            result = default; return false;");
                    sb.AppendLine("#endif");
                    break;
            }
            sb.AppendLine("        }");
        }

        private static void EmitParseSpan(StringBuilder sb, string typeName, SupportedValueType valueType)
        {
            sb.Append("        public static ").Append(typeName).AppendLine(" Parse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider)");
            sb.AppendLine("        {");
            switch (valueType)
            {
                case SupportedValueType.Guid:
                    sb.Append("            return new ").Append(typeName).AppendLine("(global::System.Guid.Parse(s, provider));");
                    break;
                case SupportedValueType.Int32:
                    sb.Append("            return new ").Append(typeName).AppendLine("(int.Parse(s, global::System.Globalization.NumberStyles.Integer, provider));");
                    break;
                case SupportedValueType.Int64:
                    sb.Append("            return new ").Append(typeName).AppendLine("(long.Parse(s, global::System.Globalization.NumberStyles.Integer, provider));");
                    break;
                case SupportedValueType.String:
                    sb.Append("            return new ").Append(typeName).AppendLine("(s.ToString());");
                    break;
                case SupportedValueType.Ulid:
                    sb.AppendLine("#if NET9_0_OR_GREATER");
                    sb.Append("            return new ").Append(typeName).AppendLine("(global::System.Ulid.Parse(s, provider));");
                    sb.AppendLine("#else");
                    sb.AppendLine("            throw new global::System.PlatformNotSupportedException(\"Ulid requires .NET 9 or later.\");");
                    sb.AppendLine("#endif");
                    break;
            }
            sb.AppendLine("        }");
        }

        private static void EmitTryParseSpan(StringBuilder sb, string typeName, SupportedValueType valueType)
        {
            sb.Append("        public static bool TryParse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider, out ").Append(typeName).AppendLine(" result)");
            sb.AppendLine("        {");
            switch (valueType)
            {
                case SupportedValueType.Guid:
                    sb.AppendLine("            if (global::System.Guid.TryParse(s, provider, out var v)) { result = new " + typeName + "(v); return true; }");
                    sb.AppendLine("            result = default; return false;");
                    break;
                case SupportedValueType.Int32:
                    sb.AppendLine("            if (int.TryParse(s, global::System.Globalization.NumberStyles.Integer, provider, out var v)) { result = new " + typeName + "(v); return true; }");
                    sb.AppendLine("            result = default; return false;");
                    break;
                case SupportedValueType.Int64:
                    sb.AppendLine("            if (long.TryParse(s, global::System.Globalization.NumberStyles.Integer, provider, out var v)) { result = new " + typeName + "(v); return true; }");
                    sb.AppendLine("            result = default; return false;");
                    break;
                case SupportedValueType.String:
                    sb.Append("            result = new ").Append(typeName).AppendLine("(s.ToString()); return true;");
                    break;
                case SupportedValueType.Ulid:
                    sb.AppendLine("#if NET9_0_OR_GREATER");
                    sb.AppendLine("            if (global::System.Ulid.TryParse(s, provider, out var v)) { result = new " + typeName + "(v); return true; }");
                    sb.AppendLine("            result = default; return false;");
                    sb.AppendLine("#else");
                    sb.AppendLine("            result = default; return false;");
                    sb.AppendLine("#endif");
                    break;
            }
            sb.AppendLine("        }");
        }
    }
}
