#nullable enable

using System.Text;

namespace Moongazing.OrionGuard.Generators.StronglyTypedIds
{
    internal static class StronglyTypedIdEmitter
    {
        public static string EmitPartial(
            string? @namespace,
            string typeName,
            SupportedValueType valueType,
            bool emitTypeConverterAttribute)
        {
            var valueCsKeyword = SupportedValueTypeMap.CSharpKeyword(valueType);
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            OpenNamespace(sb, @namespace);

            // Without this attribute TypeDescriptor found no converter, so model binding failed. The JSON
            // converter is deliberately NOT attached: ids already stored as {"Value":"..."} must keep
            // deserializing, and this deprecated generator is not the place for a wire-format change.
            // Consumers who want the bare-value shape register the generated <TypeName>JsonConverter.
            if (emitTypeConverterAttribute)
            {
                sb.Append("    [global::System.ComponentModel.TypeConverterAttribute(typeof(")
                  .Append(typeName).AppendLine("TypeConverter))]");
            }

            sb.Append("    public readonly partial struct ").Append(typeName)
              .Append(" : global::System.IEquatable<").Append(typeName).Append(">")
              .Append(", global::Moongazing.OrionGuard.Domain.Primitives.IStronglyTypedId<").Append(valueCsKeyword).AppendLine(">")
              .AppendLine("    {");
            sb.Append("        public ").Append(valueCsKeyword).AppendLine(" Value { get; }");
            sb.AppendLine();
            sb.Append("        public ").Append(typeName).Append("(").Append(valueCsKeyword).AppendLine(" value) => Value = value;");
            sb.AppendLine();

            // default(TId) of a string-backed id holds a null Value, so every member must tolerate null;
            // Value.Equals / Value.GetHashCode / Value.ToString threw NullReferenceException.
            sb.Append("        public bool Equals(").Append(typeName)
              .Append(" other) => global::System.Collections.Generic.EqualityComparer<").Append(valueCsKeyword)
              .AppendLine(">.Default.Equals(Value, other.Value);");
            sb.Append("        public override bool Equals(object? obj) => obj is ").Append(typeName).AppendLine(" other && Equals(other);");
            sb.Append("        public override int GetHashCode() => global::System.Collections.Generic.EqualityComparer<")
              .Append(valueCsKeyword).AppendLine(">.Default.GetHashCode(Value);");
            if (valueType == SupportedValueType.String)
            {
                sb.AppendLine("        public override string ToString() => Value ?? string.Empty;");
            }
            else
            {
                sb.AppendLine("        public override string ToString() => Value.ToString() ?? string.Empty;");
            }

            sb.Append("        public static bool operator ==(").Append(typeName).Append(" left, ").Append(typeName).AppendLine(" right) => left.Equals(right);");
            sb.Append("        public static bool operator !=(").Append(typeName).Append(" left, ").Append(typeName).AppendLine(" right) => !left.Equals(right);");

            if (valueType == SupportedValueType.Guid)
            {
                sb.Append("        public static ").Append(typeName).AppendLine(" New() => new(global::System.Guid.NewGuid());");
                sb.Append("        public static ").Append(typeName).AppendLine(" Empty => new(global::System.Guid.Empty);");
            }
            else if (valueType == SupportedValueType.Ulid)
            {
                sb.AppendLine("#if NET9_0_OR_GREATER");
                sb.Append("        public static ").Append(typeName).AppendLine(" New() => new(global::System.Ulid.NewUlid());");
                sb.Append("        public static ").Append(typeName).AppendLine(" Empty => new(default(global::System.Ulid));");
                sb.AppendLine("#endif");
            }

            sb.AppendLine("    }");
            CloseNamespace(sb, @namespace);

            return sb.ToString();
        }

        /// <summary>
        /// Opens the namespace block, or nothing for a type in the global namespace, which used to be
        /// emitted as <c>namespace &lt;global namespace&gt;</c> (CS1001). Members keep their four-space
        /// indent either way.
        /// </summary>
        internal static void OpenNamespace(StringBuilder sb, string? @namespace)
        {
            if (@namespace is null)
            {
                return;
            }

            sb.Append("namespace ").AppendLine(@namespace);
            sb.AppendLine("{");
        }

        internal static void CloseNamespace(StringBuilder sb, string? @namespace)
        {
            if (@namespace is not null)
            {
                sb.AppendLine("}");
            }
        }
    }
}
