#nullable enable

using System.Text;

namespace Moongazing.OrionGuard.Generators.StronglyTypedIds
{
    internal static class StronglyTypedIdEmitter
    {
        public static string EmitPartial(string @namespace, string typeName, SupportedValueType valueType)
        {
            var valueCsKeyword = SupportedValueTypeMap.CSharpKeyword(valueType);
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.Append("namespace ").AppendLine(@namespace);
            sb.AppendLine("{");
            sb.Append("    public readonly partial struct ").Append(typeName)
              .Append(" : global::System.IEquatable<").Append(typeName).Append(">")
              .Append(", global::Moongazing.OrionGuard.Domain.Primitives.IStronglyTypedId<").Append(valueCsKeyword).AppendLine(">")
              .AppendLine("    {");
            sb.Append("        public ").Append(valueCsKeyword).AppendLine(" Value { get; }");
            sb.AppendLine();
            sb.Append("        public ").Append(typeName).Append("(").Append(valueCsKeyword).AppendLine(" value) => Value = value;");
            sb.AppendLine();
            sb.Append("        public bool Equals(").Append(typeName).AppendLine(" other) => Value.Equals(other.Value);");
            sb.Append("        public override bool Equals(object? obj) => obj is ").Append(typeName).AppendLine(" other && Equals(other);");
            sb.AppendLine("        public override int GetHashCode() => Value.GetHashCode();");
            sb.AppendLine("        public override string ToString() => Value.ToString() ?? string.Empty;");
            sb.Append("        public static bool operator ==(").Append(typeName).Append(" left, ").Append(typeName).AppendLine(" right) => left.Equals(right);");
            sb.Append("        public static bool operator !=(").Append(typeName).Append(" left, ").Append(typeName).AppendLine(" right) => !left.Equals(right);");

            if (valueType == SupportedValueType.Guid)
            {
                sb.Append("        public static ").Append(typeName).AppendLine(" New() => new(global::System.Guid.NewGuid());");
                sb.Append("        public static ").Append(typeName).AppendLine(" Empty => new(global::System.Guid.Empty);");
            }
            else if (valueType == SupportedValueType.Ulid)
            {
                sb.AppendLine("#if NET9_0_OR_GREATER");
                sb.Append("        public static ").Append(typeName).AppendLine(" New() => new(global::System.Ulid.NewUlid());");
                sb.Append("        public static ").Append(typeName).AppendLine(" Empty => new(default(global::System.Ulid));");
                sb.AppendLine("#endif");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
