#nullable enable

namespace Moongazing.OrionGuard.Generators.StronglyTypedIds
{
    /// <summary>
    /// Text source of the <c>[StronglyTypedId]</c> attribute — injected into each compilation
    /// via <c>RegisterPostInitializationOutput</c>.
    /// </summary>
    internal static class StronglyTypedIdAttributeSource
    {
        public const string FullName = "Moongazing.OrionGuard.Domain.Primitives.StronglyTypedIdAttribute";

        public const string Source = @"// <auto-generated/>
#nullable enable

namespace Moongazing.OrionGuard.Domain.Primitives
{
    /// <summary>
    /// Marks a readonly partial struct as a strongly-typed id backed by the specified primitive type.
    /// The OrionGuard source generator emits equality, comparison, conversion members, as well as
    /// EF Core ValueConverter, System.Text.Json converter, and TypeConverter companion types.
    /// </summary>
    /// <typeparam name=""TValue"">Underlying primitive type. Supported: System.Guid, int, long,
    /// string, System.Ulid (net9.0+).</typeparam>
    [System.AttributeUsage(System.AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
    internal sealed class StronglyTypedIdAttribute<TValue> : System.Attribute { }
}
";
    }
}
