#nullable enable

using System.Text;

namespace Moongazing.OrionGuard.Generators.StronglyTypedIds
{
    internal static class TypeConverterEmitter
    {
        public static string Emit(string @namespace, string typeName, SupportedValueType valueType)
        {
            var converterName = typeName + "TypeConverter";

            var parseExpr = valueType switch
            {
                SupportedValueType.Guid   => "global::System.Guid.Parse(s)",
                SupportedValueType.Int32  => "int.Parse(s, global::System.Globalization.CultureInfo.InvariantCulture)",
                SupportedValueType.Int64  => "long.Parse(s, global::System.Globalization.CultureInfo.InvariantCulture)",
                SupportedValueType.String => "s",
                SupportedValueType.Ulid   => "global::System.Ulid.Parse(s)",
                _ => "default"
            };

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.Append("namespace ").AppendLine(@namespace);
            sb.AppendLine("{");
            sb.Append("    public sealed class ").Append(converterName)
              .AppendLine(" : global::System.ComponentModel.TypeConverter");
            sb.AppendLine("    {");
            sb.AppendLine("        public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Type sourceType)");
            sb.AppendLine("            => sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);");
            sb.AppendLine();
            sb.AppendLine("        public override object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object value)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (value is string s)");
            sb.Append("                return new ").Append(typeName).Append("(").Append(parseExpr).AppendLine(");");
            sb.AppendLine("            return base.ConvertFrom(context, culture, value);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public override object? ConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object? value, global::System.Type destinationType)");
            sb.AppendLine("        {");
            sb.Append("            if (destinationType == typeof(string) && value is ").Append(typeName).AppendLine(" id)");
            sb.AppendLine("                return id.Value?.ToString() ?? string.Empty;");
            sb.AppendLine("            return base.ConvertTo(context, culture, value, destinationType);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        public static string HintName(string typeName) => typeName + "TypeConverter.g.cs";
    }
}
