using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Text;

namespace Moongazing.OrionGuard.SchemaExport;

/// <summary>
/// Turns a model into a TypeScript <c>interface</c> declaration, with the OrionGuard rules
/// declared on each member written as a doc comment, so the frontend types match the contract
/// the server validates.
/// </summary>
/// <remarks>
/// <para>
/// The output is types only: the constraints are documented, never emitted as runtime checks.
/// A member whose rule the exporter cannot express -- a custom predicate, a comparison against a
/// second property -- carries a <c>// not enforced here:</c> comment naming the rule, so the
/// gap is visible in the file the frontend reads.
/// </para>
/// <para>
/// A member is marked optional (<c>?</c>) when no OrionGuard rule requires it. Rules registered
/// on an <c>AbstractValidator&lt;T&gt;</c> or built with <c>Validate.For</c> are C# delegates and
/// are invisible to reflection, so they are not reflected in the declaration.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// var declaration = TypeScriptExporter.Export&lt;CreateUserRequest&gt;();
/// File.WriteAllText("create-user.ts", declaration);
/// </code>
/// </example>
public static class TypeScriptExporter
{
    /// <summary>
    /// Exports <typeparamref name="T"/> as a TypeScript interface declaration. Nested object types
    /// reachable from it get their own interface in the same output.
    /// </summary>
    /// <typeparam name="T">The model whose members and validation attributes are exported.</typeparam>
    /// <returns>The declaration text. Lines are separated with <c>\n</c> on every platform.</returns>
    [RequiresUnreferencedCode(SchemaExportAnnotations.UnreferencedCode)]
    public static string Export<T>()
    {
        var model = ExportModel.Build(typeof(T));
        var builder = new StringBuilder();

        builder.Append("// Generated by OrionGuard.SchemaExport from ")
            .Append(model.Root.FullName ?? model.Root.Name)
            .Append(".\n// Types only: the constraints below are documented here, not enforced here.\n");

        foreach (var type in model.Types)
        {
            builder.Append("\nexport interface ").Append(model.Names[type]).Append(" {\n");

            foreach (var member in model.MembersOf(type))
            {
                foreach (var rule in member.Unsupported)
                {
                    builder.Append("  // not enforced here: ").Append(rule).Append('\n');
                }

                if (Describe(member) is { Length: > 0 } description)
                {
                    builder.Append("  /** ").Append(description).Append(" */\n");
                }

                builder.Append("  ").Append(Signature(member))
                    .Append(": ").Append(TypeScriptType(model, member.Shape)).Append(";\n");
            }

            builder.Append("}\n");
        }

        return builder.ToString();
    }

    /// <summary>
    /// The member's name and optional marker. A serialized name that is not a valid TypeScript
    /// identifier -- anything from a <c>[JsonPropertyName("first-name")]</c> -- has to be written
    /// as a quoted string, or the declaration does not parse and the whole file is unusable.
    /// </summary>
    private static string Signature(MemberModel member)
    {
        var name = IsIdentifier(member.Name) ? member.Name : Quote(member.Name);
        return member.IsRequired ? name : name + "?";
    }

    private static bool IsIdentifier(string name)
    {
        if (name.Length == 0 || (!char.IsLetter(name[0]) && name[0] != '_' && name[0] != '$'))
        {
            return false;
        }

        for (var index = 1; index < name.Length; index++)
        {
            if (!char.IsLetterOrDigit(name[index]) && name[index] != '_' && name[index] != '$')
            {
                return false;
            }
        }

        return true;
    }

    private static string Quote(string name)
    {
        var quoted = new StringBuilder(name.Length + 2).Append('"');

        foreach (var character in name)
        {
            switch (character)
            {
                case '"':
                    quoted.Append("\\\"");
                    break;
                case '\\':
                    quoted.Append("\\\\");
                    break;
                case '\n':
                    quoted.Append("\\n");
                    break;
                case '\r':
                    quoted.Append("\\r");
                    break;
                case '\t':
                    quoted.Append("\\t");
                    break;
                default:
                    if (char.IsControl(character))
                    {
                        quoted.Append("\\u").Append(((int)character).ToString("x4", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        quoted.Append(character);
                    }
                    break;
            }
        }

        return quoted.Append('"').ToString();
    }

    /// <summary>
    /// Renders the member's constraints as prose. Empty when the member carries no rule the
    /// exporter could read, so an unannotated member gets no comment at all.
    /// </summary>
    private static string Describe(MemberModel member)
    {
        if (!member.HasConstraints)
        {
            return string.Empty;
        }

        var parts = new List<string>();

        if (member.IsRequired)
        {
            parts.Add("required");
        }

        // A length rule on a collection bounds the number of items, not the number of characters.
        var collection = member.Shape.Element is not null;

        // "not blank" already says "at least 1 character", so a bare [NotEmpty] does not say it twice.
        var lengthIsImpliedByNotBlank =
            member.RequiresNonWhitespace && member.MinLength == 1 && member.MaxLength is null;

        switch (member.MinLength, member.MaxLength)
        {
            case (_, _) when lengthIsImpliedByNotBlank:
                break;
            case ({ } min, { } max):
                parts.Add($"{min} to {max} {Unit(max, collection)}");
                break;
            case ({ } min, null):
                parts.Add($"at least {min} {Unit(min, collection)}");
                break;
            case (null, { } max):
                parts.Add($"at most {max} {Unit(max, collection)}");
                break;
            default:
                break;
        }

        if (member.RequiresNonWhitespace)
        {
            parts.Add("not blank");
        }

        switch (member.Minimum, member.Maximum)
        {
            case ({ } min, { } max):
                parts.Add($"between {Number(min)} and {Number(max)}");
                break;
            case ({ } min, null):
                parts.Add($"at least {Number(min)}");
                break;
            case (null, { } max):
                parts.Add($"at most {Number(max)}");
                break;
            default:
                break;
        }

        if (member.ExclusiveMinimum is { } exclusiveMinimum)
        {
            parts.Add($"greater than {Number(exclusiveMinimum)}");
        }

        foreach (var pattern in member.Patterns)
        {
            parts.Add($"pattern: {pattern}");
        }

        if (member.Format is { } format)
        {
            parts.Add($"format: {format}");
        }

        return string.Join("; ", parts);
    }

    private static string Unit(int bound, bool collection) => (collection, bound) switch
    {
        (true, 1) => "item",
        (true, _) => "items",
        (false, 1) => "character",
        (false, _) => "characters"
    };

    private static string Number(double value) => value.ToString(CultureInfo.InvariantCulture);

    [RequiresUnreferencedCode(SchemaExportAnnotations.UnreferencedCode)]
    private static string TypeScriptType(ExportModel model, ShapeModel shape)
    {
        var declaration = BaseType(model, shape);
        return shape.IsNullable ? $"{declaration} | null" : declaration;
    }

    [RequiresUnreferencedCode(SchemaExportAnnotations.UnreferencedCode)]
    private static string BaseType(ExportModel model, ShapeModel shape)
    {
        if (model.Names.TryGetValue(shape.ClrType, out var name))
        {
            return name;
        }

        if (shape.Element is { } element)
        {
            var elementType = TypeScriptType(model, element);

            // A union element has to be parenthesised or the [] binds to its last member only.
            return elementType.Contains('|', StringComparison.Ordinal)
                ? $"({elementType})[]"
                : $"{elementType}[]";
        }

        if (shape.ClrType.IsEnum)
        {
            // Exported by name, matching the JSON Schema enum and what JsonStringEnumConverter writes.
            return string.Join(" | ", Enum.GetNames(shape.ClrType).Select(value => $"'{value}'"));
        }

        if (TypeShapes.IsDictionary(shape.ClrType))
        {
            return "Record<string, unknown>";
        }

        return TypeShapes.ScalarJsonType(shape.ClrType) switch
        {
            "boolean" => "boolean",
            "integer" or "number" => "number",
            "string" => "string",
            _ => "unknown"
        };
    }
}
