#nullable enable

using System.Collections.Generic;
using System.Globalization;
using System.Text;
using Moongazing.OrionGuard.OpenApi.Json;
using Moongazing.OrionGuard.OpenApi.Model;

namespace Moongazing.OrionGuard.OpenApi.Emit
{
    /// <summary>
    /// Emits the C# source for an OrionGuard validator derived from a resolved OpenAPI schema.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The generated type is a partial class that implements
    /// <c>Moongazing.OrionGuard.DependencyInjection.IValidator&lt;T&gt;</c> and returns a real
    /// <c>Moongazing.OrionGuard.Core.GuardResult</c>, so a generated validator is interchangeable with a
    /// hand-written one anywhere an <c>IValidator&lt;T&gt;</c> is consumed (ASP.NET Core filter, MediatR
    /// behaviour, manual call).
    /// </para>
    /// <para>
    /// Every constraint is gated on the validated member's <see cref="MemberTypeCategory"/>: a string
    /// length check is only emitted for a string member, a numeric range only for a numeric member, and
    /// so on. This keeps the emitted code compiling under the consumer's <c>TreatWarningsAsErrors</c>
    /// even when the document and the POCO disagree about a property's shape.
    /// </para>
    /// </remarks>
    internal static class ValidatorEmitter
    {
        private const string GuardResult = "global::Moongazing.OrionGuard.Core.GuardResult";
        private const string ValidationError = "global::Moongazing.OrionGuard.Core.ValidationError";
        private const string IValidator = "global::Moongazing.OrionGuard.DependencyInjection.IValidator";
        private const string Regex = "global::System.Text.RegularExpressions.Regex";

        public static string Emit(ValidatorEmitModel model)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
            string indent = hasNamespace ? "    " : string.Empty;

            if (hasNamespace)
            {
                sb.Append("namespace ").AppendLine(model.Namespace);
                sb.AppendLine("{");
            }

            sb.Append(indent).AppendLine("/// <summary>");
            sb.Append(indent).Append("/// OpenAPI-derived validator for <see cref=\"")
                .Append(model.ValidatedTypeFullName).AppendLine("\"/>.");
            sb.Append(indent).AppendLine("/// Generated from the referenced OpenAPI schema; do not edit by hand.");
            sb.Append(indent).AppendLine("/// </summary>");
            string accessibility = string.IsNullOrEmpty(model.Accessibility) ? "internal" : model.Accessibility;
            sb.Append(indent).Append(accessibility).Append(" partial class ").Append(model.ClassName)
                .Append(" : ").Append(IValidator).Append('<').Append(model.ValidatedTypeFullName).AppendLine(">");
            sb.Append(indent).AppendLine("{");

            EmitValidateMethod(sb, model, indent + "    ");
            sb.AppendLine();
            EmitValidateAsyncMethod(sb, model, indent + "    ");

            sb.Append(indent).AppendLine("}");

            if (hasNamespace)
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static void EmitValidateMethod(StringBuilder sb, ValidatorEmitModel model, string indent)
        {
            string t = model.ValidatedTypeFullName;

            sb.Append(indent).AppendLine("/// <summary>");
            sb.Append(indent).AppendLine("/// Validates the instance against the OpenAPI schema constraints.");
            sb.Append(indent).AppendLine("/// </summary>");
            sb.Append(indent).Append("public ").Append(GuardResult).Append(" Validate(").Append(t).AppendLine(" value)");
            sb.Append(indent).AppendLine("{");

            string body = indent + "    ";
            sb.Append(body).Append("var __errors = new global::System.Collections.Generic.List<")
                .Append(ValidationError).AppendLine(">();");
            sb.Append(body).AppendLine("if (value is null)");
            sb.Append(body).AppendLine("{");
            sb.Append(body).Append("    __errors.Add(new ").Append(ValidationError)
                .AppendLine("(\"\", \"The value cannot be null.\", \"NULL\"));");
            sb.Append(body).Append("    return ").Append(GuardResult).AppendLine(".Failure(__errors);");
            sb.Append(body).AppendLine("}");
            sb.AppendLine();

            foreach (var property in model.Properties)
            {
                EmitProperty(sb, property, body);
            }

            sb.Append(body).Append("return __errors.Count == 0 ? ").Append(GuardResult)
                .Append(".Success() : ").Append(GuardResult).AppendLine(".Failure(__errors);");
            sb.Append(indent).AppendLine("}");
        }

        private static void EmitValidateAsyncMethod(StringBuilder sb, ValidatorEmitModel model, string indent)
        {
            string t = model.ValidatedTypeFullName;

            sb.Append(indent).AppendLine("/// <summary>");
            sb.Append(indent).AppendLine("/// Asynchronous entry point. The generated schema rules are synchronous,");
            sb.Append(indent).AppendLine("/// so this simply wraps <see cref=\"Validate\"/> for the IValidator contract.");
            sb.Append(indent).AppendLine("/// </summary>");
            sb.Append(indent)
                .Append("public global::System.Threading.Tasks.Task<").Append(GuardResult)
                .Append("> ValidateAsync(").Append(t)
                .AppendLine(" value, global::System.Threading.CancellationToken cancellationToken = default)");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).AppendLine("    cancellationToken.ThrowIfCancellationRequested();");
            sb.Append(indent).Append("    return global::System.Threading.Tasks.Task.FromResult(Validate(value));");
            sb.AppendLine();
            sb.Append(indent).AppendLine("}");
        }

        private static void EmitProperty(StringBuilder sb, PropertyBinding property, string indent)
        {
            var schema = property.Schema;
            string member = "value." + property.MemberName;
            string errorKey = Escape(property.SchemaName);

            sb.Append(indent).Append("// Property: ").Append(property.SchemaName).AppendLine();

            // Required: the property key must be present. For a deserialized POCO a missing key surfaces
            // as null on a reference type, so required maps to a non-null check on reference members.
            if (property.Required && property.MemberIsReferenceType)
            {
                sb.Append(indent).Append("if (").Append(member).AppendLine(" is null)");
                AppendError(sb, indent + "    ", errorKey,
                    $"{property.SchemaName} is required.", "REQUIRED");
            }

            // The remaining constraints only make sense for a present value. Guard nullable/reference
            // members with a null check so a null value short-circuits to just the required rule above.
            bool needsNullGuard = property.MemberIsReferenceType;
            string checkIndent = indent;
            if (needsNullGuard)
            {
                sb.Append(indent).Append("if (").Append(member).AppendLine(" is not null)");
                sb.Append(indent).AppendLine("{");
                checkIndent = indent + "    ";
            }

            switch (property.Category)
            {
                case MemberTypeCategory.String:
                    EmitStringConstraints(sb, schema, member, errorKey, property.SchemaName, checkIndent);
                    EmitEnumConstraint(sb, schema, member, errorKey, property.SchemaName, checkIndent, quoteAsString: true);
                    break;

                case MemberTypeCategory.Numeric:
                    EmitNumericConstraints(sb, schema, member, errorKey, property.SchemaName, checkIndent,
                        property.MemberIsReferenceType, property.NumericKind);
                    EmitEnumConstraint(sb, schema, member, errorKey, property.SchemaName, checkIndent,
                        quoteAsString: false, property.NumericKind);
                    break;

                case MemberTypeCategory.Collection:
                    EmitArrayConstraints(sb, schema, member, errorKey, property.SchemaName, checkIndent);
                    break;
            }

            if (needsNullGuard)
            {
                sb.Append(indent).AppendLine("}");
            }

            sb.AppendLine();
        }

        private static void EmitStringConstraints(
            StringBuilder sb, OpenApiSchema schema, string member, string errorKey, string name, string indent)
        {
            if (schema.MinLength is int minLength)
            {
                sb.Append(indent).Append("if (").Append(member).Append(".Length < ")
                    .Append(minLength.ToString(CultureInfo.InvariantCulture)).AppendLine(")");
                AppendError(sb, indent + "    ", errorKey,
                    $"{name} must be at least {minLength} character(s) long.", "MIN_LENGTH");
            }

            if (schema.MaxLength is int maxLength)
            {
                sb.Append(indent).Append("if (").Append(member).Append(".Length > ")
                    .Append(maxLength.ToString(CultureInfo.InvariantCulture)).AppendLine(")");
                AppendError(sb, indent + "    ", errorKey,
                    $"{name} must be at most {maxLength} character(s) long.", "MAX_LENGTH");
            }

            if (!string.IsNullOrEmpty(schema.Pattern))
            {
                string pattern = VerbatimPattern(schema.Pattern!);
                sb.Append(indent).Append("if (!").Append(Regex).Append(".IsMatch(").Append(member)
                    .Append(", @\"").Append(pattern).AppendLine("\"))");
                AppendError(sb, indent + "    ", errorKey,
                    $"{name} does not match the required pattern.", "PATTERN");
            }

            EmitFormatConstraint(sb, schema, member, errorKey, name, indent);
        }

        private static void EmitFormatConstraint(
            StringBuilder sb, OpenApiSchema schema, string member, string errorKey, string name, string indent)
        {
            if (string.IsNullOrEmpty(schema.Format))
            {
                return;
            }

            // Each supported format maps to an anchored regex. The email/uuid/uri/date-time patterns mirror
            // the conventions used by the in-box OrionGuard.Generators email check; the remainder are
            // documented regexes. Unknown formats are ignored (an open-ended set in OpenAPI).
            string? formatPattern = schema.Format switch
            {
                "email" => @"^[^@\s]+@[^@\s]+\.[^@\s]+$",
                "uuid" => @"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
                "date-time" => @"^\d{4}-\d{2}-\d{2}[Tt]\d{2}:\d{2}:\d{2}(\.\d+)?([Zz]|[+-]\d{2}:\d{2})?$",
                "date" => @"^\d{4}-\d{2}-\d{2}$",
                "uri" => @"^[A-Za-z][A-Za-z0-9+.-]*:.+$",
                "hostname" => @"^(?=.{1,253}$)([A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*$",
                "ipv4" => @"^((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)\.){3}(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)$",
                _ => null,
            };

            if (formatPattern is null)
            {
                return;
            }

            sb.Append(indent).Append("if (!").Append(Regex).Append(".IsMatch(").Append(member)
                .Append(", @\"").Append(formatPattern).AppendLine("\"))");
            AppendError(sb, indent + "    ", errorKey,
                $"{name} must be a valid {schema.Format} value.", "FORMAT");
        }

        private static void EmitNumericConstraints(
            StringBuilder sb, OpenApiSchema schema, string member, string errorKey, string name,
            string indent, bool memberIsNullable, NumericKind numericKind)
        {
            // For a Nullable<T> member that survived the null guard, read .Value so the comparison is
            // against the underlying numeric type.
            string rawOperand = memberIsNullable ? member + ".Value" : member;

            if (schema.Minimum is string minimum && TryRenderBound(minimum, numericKind, out var minRender))
            {
                string operand = WrapOperand(rawOperand, minRender.OperandCast);
                string op = schema.ExclusiveMinimum ? "<=" : "<";
                sb.Append(indent).Append("if (").Append(operand).Append(' ').Append(op).Append(' ')
                    .Append(minRender.Literal).AppendLine(")");
                string boundWord = schema.ExclusiveMinimum ? "greater than" : "greater than or equal to";
                AppendError(sb, indent + "    ", errorKey,
                    $"{name} must be {boundWord} {minimum}.", "MINIMUM");
            }

            if (schema.Maximum is string maximum && TryRenderBound(maximum, numericKind, out var maxRender))
            {
                string operand = WrapOperand(rawOperand, maxRender.OperandCast);
                string op = schema.ExclusiveMaximum ? ">=" : ">";
                sb.Append(indent).Append("if (").Append(operand).Append(' ').Append(op).Append(' ')
                    .Append(maxRender.Literal).AppendLine(")");
                string boundWord = schema.ExclusiveMaximum ? "less than" : "less than or equal to";
                AppendError(sb, indent + "    ", errorKey,
                    $"{name} must be {boundWord} {maximum}.", "MAXIMUM");
            }
        }

        private static string WrapOperand(string operand, string? cast) =>
            cast is null ? operand : "(" + cast + ")(" + operand + ")";

        private static void EmitArrayConstraints(
            StringBuilder sb, OpenApiSchema schema, string member, string errorKey, string name, string indent)
        {
            if (schema.MinItems is null && schema.MaxItems is null)
            {
                return;
            }

            // Count without assuming ICollection: a single Linq count covers arrays, lists, and any
            // IEnumerable. Cached into a local so min and max share one enumeration.
            sb.Append(indent).Append("var __count_").Append(SanitizeIdentifier(name)).Append(" = global::System.Linq.Enumerable.Count(")
                .Append("global::System.Linq.Enumerable.Cast<object>(").Append(member).AppendLine("));");
            string countVar = "__count_" + SanitizeIdentifier(name);

            if (schema.MinItems is int minItems)
            {
                sb.Append(indent).Append("if (").Append(countVar).Append(" < ")
                    .Append(minItems.ToString(CultureInfo.InvariantCulture)).AppendLine(")");
                AppendError(sb, indent + "    ", errorKey,
                    $"{name} must contain at least {minItems} item(s).", "MIN_ITEMS");
            }

            if (schema.MaxItems is int maxItems)
            {
                sb.Append(indent).Append("if (").Append(countVar).Append(" > ")
                    .Append(maxItems.ToString(CultureInfo.InvariantCulture)).AppendLine(")");
                AppendError(sb, indent + "    ", errorKey,
                    $"{name} must contain at most {maxItems} item(s).", "MAX_ITEMS");
            }
        }

        private static void EmitEnumConstraint(
            StringBuilder sb, OpenApiSchema schema, string member, string errorKey, string name,
            string indent, bool quoteAsString, NumericKind numericKind = NumericKind.None)
        {
            if (schema.EnumValues.Count == 0)
            {
                return;
            }

            // For a numeric enum, render every allowed value through the same kind-aware bound logic the
            // range checks use, so the comparison operand and literal share a type that compiles. All
            // values of one schema enum render with the same operand cast.
            string? operandCast = null;
            var rendered = new List<string>();
            foreach (var value in schema.EnumValues)
            {
                if (quoteAsString)
                {
                    string? s = value.AsString();
                    if (s is not null)
                    {
                        rendered.Add("\"" + Escape(s) + "\"");
                    }
                }
                else
                {
                    string? raw = value.RawNumber();
                    if (raw is not null && TryRenderBound(raw, numericKind, out var boundRender))
                    {
                        operandCast = boundRender.OperandCast;
                        rendered.Add(boundRender.Literal);
                    }
                }
            }

            if (rendered.Count == 0)
            {
                return;
            }

            string comparand = quoteAsString ? member : WrapOperand(member, operandCast);

            sb.Append(indent).Append("if (");
            for (int i = 0; i < rendered.Count; i++)
            {
                if (i > 0)
                {
                    sb.Append(" && ");
                }

                if (quoteAsString)
                {
                    sb.Append("!global::System.String.Equals(").Append(member).Append(", ")
                        .Append(rendered[i]).Append(", global::System.StringComparison.Ordinal)");
                }
                else
                {
                    sb.Append(comparand).Append(" != ").Append(rendered[i]);
                }
            }

            sb.AppendLine(")");
            string allowed = string.Join(", ", EnumDisplay(schema, quoteAsString));
            AppendError(sb, indent + "    ", errorKey,
                $"{name} must be one of: {allowed}.", "ENUM");
        }

        private static IEnumerable<string> EnumDisplay(OpenApiSchema schema, bool quoteAsString)
        {
            foreach (var value in schema.EnumValues)
            {
                if (quoteAsString)
                {
                    if (value.AsString() is string s)
                    {
                        yield return s;
                    }
                }
                else if (value.RawNumber() is string raw)
                {
                    yield return raw;
                }
            }
        }

        private static void AppendError(StringBuilder sb, string indent, string key, string message, string code)
        {
            sb.Append(indent).Append("__errors.Add(new ").Append(ValidationError)
                .Append("(\"").Append(key).Append("\", \"").Append(Escape(message)).Append("\", \"")
                .Append(code).AppendLine("\"));");
        }

        /// <summary>
        /// One rendered numeric bound: the C# literal plus an optional cast to apply to the member operand
        /// so the comparison is between two values of the same type and compiles under
        /// <c>TreatWarningsAsErrors</c>.
        /// </summary>
        private readonly struct BoundRender
        {
            public BoundRender(string literal, string? operandCast)
            {
                Literal = literal;
                OperandCast = operandCast;
            }

            /// <summary>The C# numeric literal (already suffixed, e.g. <c>1.5m</c> or <c>42d</c>).</summary>
            public string Literal { get; }

            /// <summary>A cast to apply to the member operand, or <c>null</c> when the member type already
            /// matches the literal type.</summary>
            public string? OperandCast { get; }
        }

        /// <summary>
        /// Renders a numeric bound so it compiles against the member's actual CLR type. Integral and
        /// <c>decimal</c> members compare in <c>decimal</c> (which losslessly represents every integral
        /// value and any decimal bound), so an unsigned or 64-bit member never trips a signed/over-range
        /// or <c>decimal</c>-vs-<c>double</c> mismatch; <c>float</c>/<c>double</c> members compare in
        /// <c>double</c>. Returns <c>false</c> for a bound that cannot be represented (it is then skipped
        /// rather than emitted as uncompilable code).
        /// </summary>
        private static bool TryRenderBound(string raw, NumericKind numericKind, out BoundRender render)
        {
            render = default;

            switch (numericKind)
            {
                case NumericKind.Decimal:
                case NumericKind.SignedIntegral:
                case NumericKind.UnsignedIntegral:
                    // Compare in decimal. A decimal literal cannot carry an exponent, so round-trip the
                    // lexeme through decimal to get a canonical, suffixable form.
                    if (decimal.TryParse(raw, NumberStyles.Float, CultureInfo.InvariantCulture, out decimal dec))
                    {
                        string literal = dec.ToString(CultureInfo.InvariantCulture) + "m";
                        string? cast = numericKind == NumericKind.Decimal ? null : "decimal";
                        render = new BoundRender(literal, cast);
                        return true;
                    }

                    // Bound is outside decimal's range (extreme exponent): fall back to a double comparison.
                    return TryRenderAsDouble(raw, castOperand: true, out render);

                case NumericKind.Single:
                case NumericKind.Double:
                    // float widens to double implicitly, so a double literal compiles for both with no cast.
                    return TryRenderAsDouble(raw, castOperand: false, out render);

                default:
                    return false;
            }
        }

        private static bool TryRenderAsDouble(string raw, bool castOperand, out BoundRender render)
        {
            render = default;
            if (!double.TryParse(raw, NumberStyles.Float, CultureInfo.InvariantCulture, out double value)
                || double.IsInfinity(value) || double.IsNaN(value))
            {
                return false;
            }

            string literal = value.ToString("R", CultureInfo.InvariantCulture) + "d";
            render = new BoundRender(literal, castOperand ? "double" : null);
            return true;
        }

        private static string Escape(string value)
        {
            return value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n");
        }

        /// <summary>Escapes a regex pattern for embedding in a C# verbatim string literal.</summary>
        private static string VerbatimPattern(string pattern) => pattern.Replace("\"", "\"\"");

        private static string SanitizeIdentifier(string value)
        {
            var sb = new StringBuilder(value.Length);
            foreach (char c in value)
            {
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            }

            return sb.ToString();
        }
    }
}
