#nullable enable

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace Moongazing.OrionGuard.Generators
{
    /// <summary>
    /// Roslyn incremental source generator that reads OrionGuard validation attributes
    /// and emits compile-time validator classes, making validation reflection-free
    /// and NativeAOT compatible.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class OrionGuardGenerator : IIncrementalGenerator
    {
        private const string GenerateValidatorAttributeFullName =
            "Moongazing.OrionGuard.Generators.GenerateValidatorAttribute";

        private const string GenerateValidatorAttributeSource = @"// <auto-generated/>
#nullable enable

namespace Moongazing.OrionGuard.Generators
{
    /// <summary>
    /// When applied to a class or struct, triggers compile-time validation code generation.
    /// The generator reads OrionGuard validation attributes and emits a static validator class
    /// that performs validation without reflection.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct)]
    internal sealed class GenerateValidatorAttribute : System.Attribute { }
}
";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Step 1: Inject the [GenerateValidator] marker attribute into the compilation.
            context.RegisterPostInitializationOutput(static ctx =>
            {
                ctx.AddSource(
                    "GenerateValidatorAttribute.g.cs",
                    SourceText.From(GenerateValidatorAttributeSource, Encoding.UTF8));
            });

            // Step 2: Find all types decorated with [GenerateValidator].
            IncrementalValuesProvider<ClassInfo?> classInfos = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    GenerateValidatorAttributeFullName,
                    predicate: static (node, _) => node is ClassDeclarationSyntax || node is StructDeclarationSyntax,
                    transform: static (ctx, ct) => GetClassInfo(ctx, ct))
                .Where(static info => info is not null);

            // Step 3: Generate a validator class for each decorated type.
            context.RegisterSourceOutput(classInfos, static (spc, classInfo) =>
            {
                if (classInfo is null)
                {
                    return;
                }

                string source = GenerateValidatorSource(classInfo);
                spc.AddSource($"{classInfo.ClassName}Validator.g.cs", SourceText.From(source, Encoding.UTF8));
            });
        }

        /// <summary>
        /// Extracts class metadata and per-property validation rules from the semantic model.
        /// </summary>
        private static ClassInfo? GetClassInfo(GeneratorAttributeSyntaxContext context, CancellationToken ct)
        {
            INamedTypeSymbol? typeSymbol = context.TargetSymbol as INamedTypeSymbol;
            if (typeSymbol is null)
            {
                return null;
            }

            ct.ThrowIfCancellationRequested();

            string? namespaceName = typeSymbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : typeSymbol.ContainingNamespace.ToDisplayString();

            string className = typeSymbol.Name;

            List<PropertyValidation> properties = new List<PropertyValidation>();

            ImmutableArray<ISymbol> members = typeSymbol.GetMembers();
            foreach (ISymbol member in members)
            {
                ct.ThrowIfCancellationRequested();

                if (!(member is IPropertySymbol property))
                {
                    continue;
                }

                if (property.DeclaredAccessibility != Accessibility.Public)
                {
                    continue;
                }

                List<ValidationRule> rules = new List<ValidationRule>();

                foreach (AttributeData attr in property.GetAttributes())
                {
                    string? attrName = attr.AttributeClass?.Name;
                    if (attrName is null)
                    {
                        continue;
                    }

                    // Strip "Attribute" suffix for matching.
                    string shortName = attrName.EndsWith("Attribute")
                        ? attrName.Substring(0, attrName.Length - "Attribute".Length)
                        : attrName;

                    // Read optional ErrorMessage from named arguments.
                    string? customMessage = null;
                    string? customErrorCode = null;
                    foreach (KeyValuePair<string, TypedConstant> namedArg in attr.NamedArguments)
                    {
                        if (namedArg.Key == "ErrorMessage" && namedArg.Value.Value is string msg)
                        {
                            customMessage = msg;
                        }
                        else if (namedArg.Key == "ErrorCode" && namedArg.Value.Value is string code)
                        {
                            customErrorCode = code;
                        }
                    }

                    switch (shortName)
                    {
                        case "NotNull":
                            rules.Add(new ValidationRule(
                                ValidationType.NotNull, null, null, null, customMessage, customErrorCode));
                            break;

                        case "NotEmpty":
                            rules.Add(new ValidationRule(
                                ValidationType.NotEmpty, null, null, null, customMessage, customErrorCode));
                            break;

                        case "Length":
                            {
                                int minLen = 0;
                                int maxLen = int.MaxValue;
                                ImmutableArray<TypedConstant> ctorArgs = attr.ConstructorArguments;
                                if (ctorArgs.Length >= 2)
                                {
                                    if (ctorArgs[0].Value is int min) minLen = min;
                                    if (ctorArgs[1].Value is int max) maxLen = max;
                                }
                                rules.Add(new ValidationRule(
                                    ValidationType.Length, minLen.ToString(), maxLen.ToString(), null, customMessage, customErrorCode));
                            }
                            break;

                        case "Email":
                            rules.Add(new ValidationRule(
                                ValidationType.Email, null, null, null, customMessage, customErrorCode));
                            break;

                        case "Range":
                            {
                                string minVal = "0";
                                string maxVal = "0";
                                ImmutableArray<TypedConstant> ctorArgs = attr.ConstructorArguments;
                                if (ctorArgs.Length >= 2)
                                {
                                    minVal = ctorArgs[0].Value?.ToString() ?? "0";
                                    maxVal = ctorArgs[1].Value?.ToString() ?? "0";
                                }
                                rules.Add(new ValidationRule(
                                    ValidationType.Range, minVal, maxVal, null, customMessage, customErrorCode));
                            }
                            break;

                        case "Positive":
                            rules.Add(new ValidationRule(
                                ValidationType.Positive, null, null, null, customMessage, customErrorCode));
                            break;

                        case "Regex":
                            {
                                string pattern = string.Empty;
                                ImmutableArray<TypedConstant> ctorArgs = attr.ConstructorArguments;
                                if (ctorArgs.Length >= 1 && ctorArgs[0].Value is string pat)
                                {
                                    pattern = pat;
                                }
                                rules.Add(new ValidationRule(
                                    ValidationType.Regex, null, null, pattern, customMessage, customErrorCode));
                            }
                            break;
                    }
                }

                if (rules.Count > 0)
                {
                    string typeName = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    bool isNullable = property.Type.NullableAnnotation == NullableAnnotation.Annotated
                                     || property.Type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;
                    bool isString = property.Type.SpecialType == SpecialType.System_String
                                    || (property.Type is INamedTypeSymbol namedType
                                        && namedType.SpecialType == SpecialType.System_String);
                    bool isReferenceType = property.Type.IsReferenceType;

                    properties.Add(new PropertyValidation(
                        property.Name, typeName, isString, isReferenceType, isNullable, rules));
                }
            }

            if (properties.Count == 0)
            {
                return null;
            }

            return new ClassInfo(namespaceName, className, properties);
        }

        /// <summary>
        /// Generates the full C# source for the validator class.
        /// </summary>
        private static string GenerateValidatorSource(ClassInfo classInfo)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            bool hasNamespace = !string.IsNullOrEmpty(classInfo.Namespace);

            if (hasNamespace)
            {
                sb.AppendLine($"namespace {classInfo.Namespace}");
                sb.AppendLine("{");
            }

            string indent = hasNamespace ? "    " : "";

            sb.AppendLine($"{indent}/// <summary>");
            sb.AppendLine($"{indent}/// Auto-generated compile-time validator for <see cref=\"{classInfo.ClassName}\"/>.");
            sb.AppendLine($"{indent}/// Performs reflection-free validation based on OrionGuard attributes.");
            sb.AppendLine($"{indent}/// </summary>");
            sb.AppendLine($"{indent}public static class {classInfo.ClassName}Validator");
            sb.AppendLine($"{indent}{{");

            // Validate method
            sb.AppendLine($"{indent}    /// <summary>");
            sb.AppendLine($"{indent}    /// Validates the specified <see cref=\"{classInfo.ClassName}\"/> instance.");
            sb.AppendLine($"{indent}    /// </summary>");
            sb.AppendLine($"{indent}    /// <param name=\"instance\">The instance to validate.</param>");
            sb.AppendLine($"{indent}    /// <returns>A <see cref=\"Moongazing.OrionGuard.Core.GuardResult\"/> indicating success or failure.</returns>");
            sb.AppendLine($"{indent}    public static Moongazing.OrionGuard.Core.GuardResult Validate({classInfo.ClassName} instance)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        var errors = new System.Collections.Generic.List<Moongazing.OrionGuard.Core.ValidationError>();");
            sb.AppendLine();

            foreach (PropertyValidation prop in classInfo.Properties)
            {
                EmitPropertyValidation(sb, prop, indent + "        ");
                sb.AppendLine();
            }

            sb.AppendLine($"{indent}        return errors.Count == 0");
            sb.AppendLine($"{indent}            ? Moongazing.OrionGuard.Core.GuardResult.Success()");
            sb.AppendLine($"{indent}            : Moongazing.OrionGuard.Core.GuardResult.Failure(errors);");
            sb.AppendLine($"{indent}    }}");

            // ValidateAndThrow method
            sb.AppendLine();
            sb.AppendLine($"{indent}    /// <summary>");
            sb.AppendLine($"{indent}    /// Validates the specified <see cref=\"{classInfo.ClassName}\"/> instance and throws if invalid.");
            sb.AppendLine($"{indent}    /// </summary>");
            sb.AppendLine($"{indent}    /// <param name=\"instance\">The instance to validate.</param>");
            sb.AppendLine($"{indent}    /// <returns>The validated instance.</returns>");
            sb.AppendLine($"{indent}    /// <exception cref=\"Moongazing.OrionGuard.Core.AggregateValidationException\">Thrown when validation fails.</exception>");
            sb.AppendLine($"{indent}    public static {classInfo.ClassName} ValidateAndThrow({classInfo.ClassName} instance)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        var result = Validate(instance);");
            sb.AppendLine($"{indent}        result.ThrowIfInvalid();");
            sb.AppendLine($"{indent}        return instance;");
            sb.AppendLine($"{indent}    }}");

            sb.AppendLine($"{indent}}}");

            if (hasNamespace)
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        /// <summary>
        /// Emits validation code for a single property based on its rules.
        /// Rules are ordered so that null checks come first, then emptiness, then format/range checks.
        /// Uses if/else if chaining so that downstream checks don't run on null/empty values.
        /// </summary>
        private static void EmitPropertyValidation(StringBuilder sb, PropertyValidation prop, string indent)
        {
            // Sort rules: NotNull first, NotEmpty second, then the rest.
            List<ValidationRule> sorted = prop.Rules
                .OrderBy(r =>
                {
                    switch (r.Type)
                    {
                        case ValidationType.NotNull: return 0;
                        case ValidationType.NotEmpty: return 1;
                        default: return 2;
                    }
                })
                .ToList();

            bool hasNullCheck = sorted.Any(r => r.Type == ValidationType.NotNull);
            bool hasEmptyCheck = sorted.Any(r => r.Type == ValidationType.NotEmpty);
            bool hasOtherRules = sorted.Any(r => r.Type != ValidationType.NotNull && r.Type != ValidationType.NotEmpty);
            bool needsElseIf = false;

            // Emit NotNull
            if (hasNullCheck)
            {
                ValidationRule rule = sorted.First(r => r.Type == ValidationType.NotNull);
                string message = EscapeString(rule.CustomMessage ?? $"{prop.Name} cannot be null.");
                string errorCode = EscapeString(rule.CustomErrorCode ?? "NOT_NULL");

                sb.AppendLine($"{indent}if (instance.{prop.Name} is null)");
                sb.AppendLine($"{indent}    errors.Add(new Moongazing.OrionGuard.Core.ValidationError(\"{prop.Name}\", \"{message}\", \"{errorCode}\"));");
                needsElseIf = true;
            }

            // Emit NotEmpty
            if (hasEmptyCheck)
            {
                ValidationRule rule = sorted.First(r => r.Type == ValidationType.NotEmpty);
                string message = EscapeString(rule.CustomMessage ?? $"{prop.Name} cannot be empty.");
                string errorCode = EscapeString(rule.CustomErrorCode ?? "NOT_EMPTY");

                string keyword = needsElseIf ? "else if" : "if";

                if (prop.IsString)
                {
                    sb.AppendLine($"{indent}{keyword} (string.IsNullOrWhiteSpace(instance.{prop.Name}))");
                }
                else
                {
                    // For collections or other types, check for null then use a general approach.
                    sb.AppendLine($"{indent}{keyword} (instance.{prop.Name} is null || (instance.{prop.Name} is System.Collections.IEnumerable __enumerable_{prop.Name} && !__enumerable_{prop.Name}.GetEnumerator().MoveNext()))");
                }

                sb.AppendLine($"{indent}    errors.Add(new Moongazing.OrionGuard.Core.ValidationError(\"{prop.Name}\", \"{message}\", \"{errorCode}\"));");
                needsElseIf = true;
            }

            // Emit remaining rules in an else block so they only run when value is non-null and non-empty.
            List<ValidationRule> remaining = sorted
                .Where(r => r.Type != ValidationType.NotNull && r.Type != ValidationType.NotEmpty)
                .ToList();

            if (remaining.Count > 0)
            {
                // If we had null/empty checks, wrap remaining in "else { ... }"
                if (needsElseIf)
                {
                    sb.AppendLine($"{indent}else");
                    sb.AppendLine($"{indent}{{");
                    string innerIndent = indent + "    ";
                    foreach (ValidationRule rule in remaining)
                    {
                        EmitSingleRule(sb, prop, rule, innerIndent);
                    }
                    sb.AppendLine($"{indent}}}");
                }
                else
                {
                    foreach (ValidationRule rule in remaining)
                    {
                        EmitSingleRule(sb, prop, rule, indent);
                    }
                }
            }
        }

        private static void EmitSingleRule(StringBuilder sb, PropertyValidation prop, ValidationRule rule, string indent)
        {
            switch (rule.Type)
            {
                case ValidationType.Length:
                    {
                        string min = rule.Min ?? "0";
                        string max = rule.Max ?? int.MaxValue.ToString();
                        string message = EscapeString(rule.CustomMessage ?? $"{prop.Name} must be between {min} and {max} characters.");
                        string errorCode = EscapeString(rule.CustomErrorCode ?? "LENGTH");

                        sb.AppendLine($"{indent}if (instance.{prop.Name} != null && (instance.{prop.Name}.Length < {min} || instance.{prop.Name}.Length > {max}))");
                        sb.AppendLine($"{indent}    errors.Add(new Moongazing.OrionGuard.Core.ValidationError(\"{prop.Name}\", \"{message}\", \"{errorCode}\"));");
                    }
                    break;

                case ValidationType.Email:
                    {
                        string message = EscapeString(rule.CustomMessage ?? $"{prop.Name} must be a valid email address.");
                        string errorCode = EscapeString(rule.CustomErrorCode ?? "EMAIL");

                        sb.AppendLine($"{indent}if (instance.{prop.Name} != null && !System.Text.RegularExpressions.Regex.IsMatch(instance.{prop.Name}, @\"^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$\"))");
                        sb.AppendLine($"{indent}    errors.Add(new Moongazing.OrionGuard.Core.ValidationError(\"{prop.Name}\", \"{message}\", \"{errorCode}\"));");
                    }
                    break;

                case ValidationType.Range:
                    {
                        string min = rule.Min ?? "0";
                        string max = rule.Max ?? "0";
                        string message = EscapeString(rule.CustomMessage ?? $"{prop.Name} must be between {min} and {max}.");
                        string errorCode = EscapeString(rule.CustomErrorCode ?? "RANGE");

                        sb.AppendLine($"{indent}if (instance.{prop.Name} < {min} || instance.{prop.Name} > {max})");
                        sb.AppendLine($"{indent}    errors.Add(new Moongazing.OrionGuard.Core.ValidationError(\"{prop.Name}\", \"{message}\", \"{errorCode}\"));");
                    }
                    break;

                case ValidationType.Positive:
                    {
                        string message = EscapeString(rule.CustomMessage ?? $"{prop.Name} must be positive.");
                        string errorCode = EscapeString(rule.CustomErrorCode ?? "POSITIVE");

                        sb.AppendLine($"{indent}if (instance.{prop.Name} <= 0)");
                        sb.AppendLine($"{indent}    errors.Add(new Moongazing.OrionGuard.Core.ValidationError(\"{prop.Name}\", \"{message}\", \"{errorCode}\"));");
                    }
                    break;

                case ValidationType.Regex:
                    {
                        string pattern = rule.Pattern ?? string.Empty;
                        string message = EscapeString(rule.CustomMessage ?? $"{prop.Name} does not match the required pattern.");
                        string errorCode = EscapeString(rule.CustomErrorCode ?? "REGEX");

                        // Escape the pattern for embedding in a verbatim string literal.
                        string escapedPattern = pattern.Replace("\"", "\"\"");

                        sb.AppendLine($"{indent}if (instance.{prop.Name} != null && !System.Text.RegularExpressions.Regex.IsMatch(instance.{prop.Name}, @\"{escapedPattern}\"))");
                        sb.AppendLine($"{indent}    errors.Add(new Moongazing.OrionGuard.Core.ValidationError(\"{prop.Name}\", \"{message}\", \"{errorCode}\"));");
                    }
                    break;
            }
        }

        private static string EscapeString(string value)
        {
            return value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"");
        }
    }

    /// <summary>
    /// Holds parsed metadata about a class/struct decorated with [GenerateValidator].
    /// </summary>
    internal sealed class ClassInfo
    {
        public string? Namespace { get; }
        public string ClassName { get; }
        public List<PropertyValidation> Properties { get; }

        public ClassInfo(string? ns, string className, List<PropertyValidation> properties)
        {
            Namespace = ns;
            ClassName = className;
            Properties = properties;
        }
    }

    /// <summary>
    /// Holds per-property validation rule information.
    /// </summary>
    internal sealed class PropertyValidation
    {
        public string Name { get; }
        public string TypeName { get; }
        public bool IsString { get; }
        public bool IsReferenceType { get; }
        public bool IsNullable { get; }
        public List<ValidationRule> Rules { get; }

        public PropertyValidation(
            string name, string typeName, bool isString,
            bool isReferenceType, bool isNullable, List<ValidationRule> rules)
        {
            Name = name;
            TypeName = typeName;
            IsString = isString;
            IsReferenceType = isReferenceType;
            IsNullable = isNullable;
            Rules = rules;
        }
    }

    /// <summary>
    /// Represents a single validation rule extracted from an attribute.
    /// </summary>
    internal sealed class ValidationRule
    {
        public ValidationType Type { get; }
        public string? Min { get; }
        public string? Max { get; }
        public string? Pattern { get; }
        public string? CustomMessage { get; }
        public string? CustomErrorCode { get; }

        public ValidationRule(
            ValidationType type, string? min, string? max,
            string? pattern, string? customMessage, string? customErrorCode)
        {
            Type = type;
            Min = min;
            Max = max;
            Pattern = pattern;
            CustomMessage = customMessage;
            CustomErrorCode = customErrorCode;
        }
    }

    /// <summary>
    /// The types of validation rules the generator recognizes.
    /// </summary>
    internal enum ValidationType
    {
        NotNull,
        NotEmpty,
        Length,
        Email,
        Range,
        Positive,
        Regex
    }
}
