#nullable enable

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading;

namespace Moongazing.OrionGuard.Generators
{
    /// <summary>
    /// Roslyn incremental source generator that reads OrionGuard validation attributes
    /// and emits compile-time validator classes, making validation reflection-free
    /// and NativeAOT compatible.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class OrionGuardGenerator : IIncrementalGenerator
    {
        private const string GenerateValidatorAttributeFullName =
            "Moongazing.OrionGuard.Generators.GenerateValidatorAttribute";

        private const string ValidationAttributeNamespace = "Moongazing.OrionGuard.Attributes";

        private const string ValidationAttributeFullName = "Moongazing.OrionGuard.Attributes.ValidationAttribute";

        private const string RegexHelperName = "MatchesWithinTimeout";

        /// <summary>
        /// OG0002: a property carries a validation attribute the generator cannot translate, so the
        /// generated validator would silently skip it.
        /// </summary>
        internal static readonly DiagnosticDescriptor UnsupportedValidationAttribute = new DiagnosticDescriptor(
            id: "OG0002",
            title: "Validation attribute is not enforced by the generated validator",
            messageFormat: "'{0}' on property '{1}' of '{2}' is a validation attribute that [GenerateValidator] does not understand, so the generated validator does not enforce it",
            category: "Usage",
            defaultSeverity: DiagnosticSeverity.Warning,
            isEnabledByDefault: true,
            description: "The [GenerateValidator] generator translates NotNull, NotEmpty, Length, Email, Range, Positive and Regex from Moongazing.OrionGuard.Attributes. Any other ValidationAttribute subclass is only honoured by the reflection-based AttributeValidator, so the generated validator accepts values that attribute would reject.",
            helpLinkUri: "https://github.com/tunahanaliozturk/OrionGuard/blob/master/src/Moongazing.OrionGuard.Generators/docs/README.md");

        /// <summary>
        /// OG0003: a property the generated validator cannot read, because its getter is not accessible from
        /// a namespace-level class in this assembly. Its rules are skipped.
        /// </summary>
        internal static readonly DiagnosticDescriptor InaccessiblePropertyGetter = new DiagnosticDescriptor(
            id: "OG0003",
            title: "Property getter is not accessible to the generated validator",
            messageFormat: "The getter of property '{0}' of '{1}' cannot be called from the generated validator, so its validation attributes are not enforced",
            category: "Usage",
            defaultSeverity: DiagnosticSeverity.Warning,
            isEnabledByDefault: true,
            description: "The generated validator is a namespace-level class in the compiling assembly, so it can only read a property whose getter is public, or internal in an assembly that grants this one access. A property with a private or protected getter is only validated by the reflection-based AttributeValidator.",
            helpLinkUri: "https://github.com/tunahanaliozturk/OrionGuard/blob/master/src/Moongazing.OrionGuard.Generators/docs/README.md");

        private const string GenerateValidatorAttributeSource = @"// <auto-generated/>
#nullable enable

namespace Moongazing.OrionGuard.Generators
{
    /// <summary>
    /// When applied to a class or struct, triggers compile-time validation code generation.
    /// The generator reads OrionGuard validation attributes and emits a static validator class
    /// that performs validation without reflection.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct)]
    internal sealed class GenerateValidatorAttribute : System.Attribute { }
}
";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Step 1: Inject the [GenerateValidator] marker attribute into the compilation.
            context.RegisterPostInitializationOutput(static ctx =>
            {
                ctx.AddSource(
                    "GenerateValidatorAttribute.g.cs",
                    SourceText.From(GenerateValidatorAttributeSource, Encoding.UTF8));
            });

            // Step 2: Find all types decorated with [GenerateValidator]. A record (class or struct) has
            // its own syntax node kind, so it is listed explicitly.
            IncrementalValuesProvider<ClassInfo?> classInfos = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    GenerateValidatorAttributeFullName,
                    predicate: static (node, _) =>
                        node is ClassDeclarationSyntax || node is StructDeclarationSyntax || node is RecordDeclarationSyntax,
                    transform: static (ctx, ct) => GetClassInfo(ctx, ct))
                .Where(static info => info is not null);

            // Step 3: Report untranslatable attributes and generate a validator class for each decorated type.
            context.RegisterSourceOutput(classInfos, static (spc, classInfo) =>
            {
                if (classInfo is null)
                {
                    return;
                }

                foreach (UnsupportedAttribute unsupported in classInfo.UnsupportedAttributes)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        UnsupportedValidationAttribute,
                        unsupported.Location.ToLocation(),
                        unsupported.AttributeName,
                        unsupported.PropertyName,
                        classInfo.ClassName));
                }

                foreach (InaccessibleMember inaccessible in classInfo.InaccessibleProperties)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        InaccessiblePropertyGetter,
                        inaccessible.Location.ToLocation(),
                        inaccessible.PropertyName,
                        classInfo.ClassName));
                }

                if (classInfo.Properties.Count == 0)
                {
                    return;
                }

                string source = GenerateValidatorSource(classInfo);
                spc.AddSource(classInfo.HintName + "Validator.g.cs", SourceText.From(source, Encoding.UTF8));
            });
        }

        /// <summary>
        /// Extracts class metadata and per-property validation rules from the semantic model.
        /// </summary>
        private static ClassInfo? GetClassInfo(GeneratorAttributeSyntaxContext context, CancellationToken ct)
        {
            INamedTypeSymbol? typeSymbol = context.TargetSymbol as INamedTypeSymbol;
            if (typeSymbol is null)
            {
                return null;
            }

            ct.ThrowIfCancellationRequested();

            string? namespaceName = typeSymbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : typeSymbol.ContainingNamespace.ToDisplayString();

            ImmutableArray<PropertyValidation>.Builder properties = ImmutableArray.CreateBuilder<PropertyValidation>();
            ImmutableArray<UnsupportedAttribute>.Builder unsupportedAttributes = ImmutableArray.CreateBuilder<UnsupportedAttribute>();
            ImmutableArray<InaccessibleMember>.Builder inaccessibleProperties = ImmutableArray.CreateBuilder<InaccessibleMember>();
            LocationInfo typeLocation = LocationInfo.From(typeSymbol.Locations[0]);

            // Walk the base types too: inherited properties are part of the instance being validated. The
            // most derived declaration of a name wins, so an override or a 'new' property shadows the base one.
            HashSet<string> seen = new HashSet<string>(StringComparer.Ordinal);
            for (INamedTypeSymbol? current = typeSymbol;
                current is not null && current.SpecialType != SpecialType.System_Object;
                current = current.BaseType)
            {
                foreach (ISymbol member in current.GetMembers())
                {
                    ct.ThrowIfCancellationRequested();

                    if (!(member is IPropertySymbol property)
                        || property.DeclaredAccessibility != Accessibility.Public
                        || property.IsStatic
                        || property.IsIndexer
                        || property.GetMethod is null)
                    {
                        continue;
                    }

                    if (!seen.Add(property.Name))
                    {
                        continue;
                    }

                    // A public property can still have a getter of its own, narrower accessibility. Emitting
                    // instance.Property for one the validator cannot call produces code that does not compile.
                    if (!IsGetterAccessible(property.GetMethod, context.SemanticModel.Compilation.Assembly))
                    {
                        if (property.GetAttributes().Length > 0)
                        {
                            inaccessibleProperties.Add(new InaccessibleMember(
                                property.Name,
                                LocationInfo.From(property.Locations.Length > 0 ? property.Locations[0] : typeSymbol.Locations[0])));
                        }
                        continue;
                    }

                    List<ValidationRule> rules = new List<ValidationRule>();

                    // An override without attributes still carries the ones declared on the property it
                    // overrides, as reflection's inherited attribute lookup does.
                    for (IPropertySymbol? declaration = property; declaration is not null; declaration = declaration.OverriddenProperty)
                    {
                        foreach (AttributeData attr in declaration.GetAttributes())
                        {
                            ReadRule(attr, property, typeLocation, rules, unsupportedAttributes, ct);
                        }
                    }

                    if (rules.Count > 0)
                    {
                        ITypeSymbol valueType = property.Type;
                        bool isNullable = valueType.NullableAnnotation == NullableAnnotation.Annotated
                                         || valueType.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;
                        if (valueType is INamedTypeSymbol named
                            && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
                        {
                            valueType = named.TypeArguments[0];
                        }

                        properties.Add(new PropertyValidation(
                            property.Name,
                            valueType.SpecialType == SpecialType.System_String,
                            isNullable,
                            valueType.SpecialType,
                            new EquatableArray<ValidationRule>(rules.ToImmutableArray())));
                    }
                }
            }

            if (properties.Count == 0 && unsupportedAttributes.Count == 0)
            {
                return null;
            }

            return new ClassInfo(
                namespaceName,
                typeSymbol.Name,
                typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                EffectiveAccessibility(typeSymbol),
                HintNames.ForType(typeSymbol),
                new EquatableArray<PropertyValidation>(properties.ToImmutable()),
                new EquatableArray<UnsupportedAttribute>(unsupportedAttributes.ToImmutable()),
                new EquatableArray<InaccessibleMember>(inaccessibleProperties.ToImmutable()));
        }

        /// <summary>
        /// Translates one attribute into a rule. Only attributes declared in
        /// <c>Moongazing.OrionGuard.Attributes</c> are matched, by full name: matching the simple name read
        /// <c>System.ComponentModel.DataAnnotations.RangeAttribute</c> as an OrionGuard range. Any other
        /// OrionGuard <c>ValidationAttribute</c> subclass is recorded for OG0002.
        /// </summary>
        private static void ReadRule(
            AttributeData attr,
            IPropertySymbol property,
            LocationInfo fallbackLocation,
            List<ValidationRule> rules,
            ImmutableArray<UnsupportedAttribute>.Builder unsupportedAttributes,
            CancellationToken ct)
        {
            INamedTypeSymbol? attributeClass = attr.AttributeClass;
            if (attributeClass is null)
            {
                return;
            }

            string? name = attributeClass.ContainingNamespace?.ToDisplayString() == ValidationAttributeNamespace
                ? attributeClass.Name
                : null;

            // Read optional ErrorMessage from named arguments.
            string? customMessage = null;
            string? customErrorCode = null;
            foreach (KeyValuePair<string, TypedConstant> namedArg in attr.NamedArguments)
            {
                if (namedArg.Key == "ErrorMessage" && namedArg.Value.Value is string msg)
                {
                    customMessage = msg;
                }
                else if (namedArg.Key == "ErrorCode" && namedArg.Value.Value is string code)
                {
                    customErrorCode = code;
                }
            }

            ImmutableArray<TypedConstant> ctorArgs = attr.ConstructorArguments;
            switch (name)
            {
                case "NotNullAttribute":
                    rules.Add(new ValidationRule(
                        ValidationType.NotNull, null, null, null, customMessage, customErrorCode));
                    break;

                case "NotEmptyAttribute":
                    rules.Add(new ValidationRule(
                        ValidationType.NotEmpty, null, null, null, customMessage, customErrorCode));
                    break;

                case "LengthAttribute":
                    {
                        int minLen = 0;
                        int maxLen = int.MaxValue;
                        if (ctorArgs.Length >= 2)
                        {
                            if (ctorArgs[0].Value is int min) minLen = min;
                            if (ctorArgs[1].Value is int max) maxLen = max;
                        }
                        rules.Add(new ValidationRule(
                            ValidationType.Length,
                            minLen.ToString(CultureInfo.InvariantCulture),
                            maxLen.ToString(CultureInfo.InvariantCulture),
                            null, customMessage, customErrorCode));
                    }
                    break;

                case "EmailAttribute":
                    rules.Add(new ValidationRule(
                        ValidationType.Email, null, null, null, customMessage, customErrorCode));
                    break;

                case "RangeAttribute":
                    {
                        string minVal = "0";
                        string maxVal = "0";
                        if (ctorArgs.Length >= 2)
                        {
                            minVal = FormatBound(ctorArgs[0]);
                            maxVal = FormatBound(ctorArgs[1]);
                        }
                        rules.Add(new ValidationRule(
                            ValidationType.Range, minVal, maxVal, null, customMessage, customErrorCode));
                    }
                    break;

                case "PositiveAttribute":
                    rules.Add(new ValidationRule(
                        ValidationType.Positive, null, null, null, customMessage, customErrorCode));
                    break;

                case "RegexAttribute":
                    {
                        string pattern = string.Empty;
                        if (ctorArgs.Length >= 1 && ctorArgs[0].Value is string pat)
                        {
                            pattern = pat;
                        }
                        rules.Add(new ValidationRule(
                            ValidationType.Regex, null, null, pattern, customMessage, customErrorCode));
                    }
                    break;

                default:
                    if (IsValidationAttribute(attributeClass))
                    {
                        // An attribute inherited from a base class compiled into another assembly has no
                        // syntax here; point at the [GenerateValidator] type instead.
                        SyntaxReference? syntax = attr.ApplicationSyntaxReference;
                        unsupportedAttributes.Add(new UnsupportedAttribute(
                            attributeClass.Name,
                            property.Name,
                            syntax is null ? fallbackLocation : LocationInfo.From(syntax.GetSyntax(ct).GetLocation())));
                    }
                    break;
            }
        }

        private static bool IsValidationAttribute(INamedTypeSymbol attributeClass)
        {
            for (INamedTypeSymbol? baseType = attributeClass.BaseType; baseType is not null; baseType = baseType.BaseType)
            {
                if (baseType.ToDisplayString() == ValidationAttributeFullName)
                {
                    return true;
                }
            }

            return false;
        }

        /// <summary>
        /// Formats a <c>[Range]</c> bound with the invariant culture. The current culture leaked into the
        /// generated code before: on a tr-TR machine 0.5 became <c>0,5</c>, which does not compile.
        /// </summary>
        private static string FormatBound(TypedConstant bound)
        {
            switch (bound.Value)
            {
                case int i:
                    return i.ToString(CultureInfo.InvariantCulture);
                case double d:
                    return d.ToString("R", CultureInfo.InvariantCulture);
                default:
                    return "0";
            }
        }

        /// <summary>
        /// A public static validator taking an internal type does not compile (CS0051), so the validator
        /// is public only when the type and every type enclosing it are public.
        /// </summary>
        private static string EffectiveAccessibility(INamedTypeSymbol type)
        {
            for (INamedTypeSymbol? current = type; current is not null; current = current.ContainingType)
            {
                if (current.DeclaredAccessibility != Accessibility.Public)
                {
                    return "internal";
                }
            }

            return "public";
        }

        /// <summary>
        /// Generates the full C# source for the validator class.
        /// </summary>
        private static string GenerateValidatorSource(ClassInfo classInfo)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            bool hasNamespace = !string.IsNullOrEmpty(classInfo.Namespace);

            if (hasNamespace)
            {
                sb.AppendLine($"namespace {classInfo.Namespace}");
                sb.AppendLine("{");
            }

            string indent = hasNamespace ? "    " : "";

            // The validated type is referenced by its fully-qualified name, so a nested target
            // (Outer.Inner) resolves from the namespace-level validator.
            string typeName = classInfo.TypeFullName;

            sb.AppendLine($"{indent}/// <summary>");
            sb.AppendLine($"{indent}/// Auto-generated compile-time validator for <see cref=\"{typeName}\"/>.");
            sb.AppendLine($"{indent}/// Performs reflection-free validation based on OrionGuard attributes.");
            sb.AppendLine($"{indent}/// </summary>");
            sb.AppendLine($"{indent}{classInfo.Accessibility} static class {classInfo.ClassName}Validator");
            sb.AppendLine($"{indent}{{");

            // Validate method
            sb.AppendLine($"{indent}    /// <summary>");
            sb.AppendLine($"{indent}    /// Validates the specified <see cref=\"{typeName}\"/> instance.");
            sb.AppendLine($"{indent}    /// </summary>");
            sb.AppendLine($"{indent}    /// <param name=\"instance\">The instance to validate.</param>");
            sb.AppendLine($"{indent}    /// <returns>A <see cref=\"Moongazing.OrionGuard.Core.GuardResult\"/> indicating success or failure.</returns>");
            sb.AppendLine($"{indent}    public static Moongazing.OrionGuard.Core.GuardResult Validate({typeName} instance)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        var errors = new System.Collections.Generic.List<Moongazing.OrionGuard.Core.ValidationError>();");
            sb.AppendLine();

            foreach (PropertyValidation prop in classInfo.Properties)
            {
                EmitPropertyValidation(sb, prop, indent + "        ");
                sb.AppendLine();
            }

            sb.AppendLine($"{indent}        return errors.Count == 0");
            sb.AppendLine($"{indent}            ? Moongazing.OrionGuard.Core.GuardResult.Success()");
            sb.AppendLine($"{indent}            : Moongazing.OrionGuard.Core.GuardResult.Failure(errors);");
            sb.AppendLine($"{indent}    }}");

            // ValidateAndThrow method
            sb.AppendLine();
            sb.AppendLine($"{indent}    /// <summary>");
            sb.AppendLine($"{indent}    /// Validates the specified <see cref=\"{typeName}\"/> instance and throws if invalid.");
            sb.AppendLine($"{indent}    /// </summary>");
            sb.AppendLine($"{indent}    /// <param name=\"instance\">The instance to validate.</param>");
            sb.AppendLine($"{indent}    /// <returns>The validated instance.</returns>");
            sb.AppendLine($"{indent}    /// <exception cref=\"Moongazing.OrionGuard.Core.AggregateValidationException\">Thrown when validation fails.</exception>");
            sb.AppendLine($"{indent}    public static {typeName} ValidateAndThrow({typeName} instance)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        var result = Validate(instance);");
            sb.AppendLine($"{indent}        result.ThrowIfInvalid();");
            sb.AppendLine($"{indent}        return instance;");
            sb.AppendLine($"{indent}    }}");

            if (classInfo.Properties.Any(p => p.Rules.Any(r => r.Type == ValidationType.Email || r.Type == ValidationType.Regex)))
            {
                EmitRegexHelper(sb, indent + "    ");
            }

            sb.AppendLine($"{indent}}}");

            if (hasNamespace)
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        /// <summary>
        /// Emits the helper every regex check goes through. The regexes carry a one-second match timeout;
        /// a match that runs past it counts as a mismatch, so hostile input yields a validation error, as
        /// the core package's result-returning APIs do, instead of a <c>RegexMatchTimeoutException</c>.
        /// </summary>
        private static void EmitRegexHelper(StringBuilder sb, string indent)
        {
            sb.AppendLine();
            sb.AppendLine($"{indent}private static bool {RegexHelperName}(global::System.Text.RegularExpressions.Regex regex, string input)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    try");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        return regex.IsMatch(input);");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}    catch (global::System.Text.RegularExpressions.RegexMatchTimeoutException)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        return false;");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");
        }

        /// <summary>
        /// Emits validation code for a single property based on its rules.
        /// Rules are ordered so that null checks come first, then emptiness, then format/range checks.
        /// Uses if/else if chaining so that downstream checks don't run on null/empty values.
        /// </summary>
        private static void EmitPropertyValidation(StringBuilder sb, PropertyValidation prop, string indent)
        {
            // Sort rules: NotNull first, NotEmpty second, then the rest.
            List<ValidationRule> sorted = prop.Rules
                .OrderBy(r =>
                {
                    switch (r.Type)
                    {
                        case ValidationType.NotNull: return 0;
                        case ValidationType.NotEmpty: return 1;
                        default: return 2;
                    }
                })
                .ToList();

            bool hasNullCheck = sorted.Any(r => r.Type == ValidationType.NotNull);
            bool hasEmptyCheck = sorted.Any(r => r.Type == ValidationType.NotEmpty);
            bool needsElseIf = false;

            // Emit NotNull
            if (hasNullCheck)
            {
                ValidationRule rule = sorted.First(r => r.Type == ValidationType.NotNull);
                string message = EscapeString(rule.CustomMessage ?? $"{prop.Name} cannot be null.");
                string errorCode = EscapeString(rule.CustomErrorCode ?? "NOT_NULL");

                sb.AppendLine($"{indent}if (instance.{prop.Name} is null)");
                sb.AppendLine($"{indent}    errors.Add(new Moongazing.OrionGuard.Core.ValidationError(\"{prop.Name}\", \"{message}\", \"{errorCode}\"));");
                needsElseIf = true;
            }

            // Emit NotEmpty
            if (hasEmptyCheck)
            {
                ValidationRule rule = sorted.First(r => r.Type == ValidationType.NotEmpty);
                string message = EscapeString(rule.CustomMessage ?? $"{prop.Name} cannot be empty.");
                string errorCode = EscapeString(rule.CustomErrorCode ?? "NOT_EMPTY");

                string keyword = needsElseIf ? "else if" : "if";

                if (prop.IsString)
                {
                    sb.AppendLine($"{indent}{keyword} (string.IsNullOrWhiteSpace(instance.{prop.Name}))");
                }
                else
                {
                    // For collections or other types, check for null then use a general approach.
                    sb.AppendLine($"{indent}{keyword} (instance.{prop.Name} is null || (instance.{prop.Name} is System.Collections.IEnumerable __enumerable_{prop.Name} && !__enumerable_{prop.Name}.GetEnumerator().MoveNext()))");
                }

                sb.AppendLine($"{indent}    errors.Add(new Moongazing.OrionGuard.Core.ValidationError(\"{prop.Name}\", \"{message}\", \"{errorCode}\"));");
                needsElseIf = true;
            }

            // Emit remaining rules in an else block so they only run when value is non-null and non-empty.
            List<ValidationRule> remaining = sorted
                .Where(r => r.Type != ValidationType.NotNull && r.Type != ValidationType.NotEmpty)
                .ToList();

            if (remaining.Count > 0)
            {
                // If we had null/empty checks, wrap remaining in "else { ... }"
                if (needsElseIf)
                {
                    sb.AppendLine($"{indent}else");
                    sb.AppendLine($"{indent}{{");
                    string innerIndent = indent + "    ";
                    foreach (ValidationRule rule in remaining)
                    {
                        EmitSingleRule(sb, prop, rule, innerIndent);
                    }
                    sb.AppendLine($"{indent}}}");
                }
                else
                {
                    foreach (ValidationRule rule in remaining)
                    {
                        EmitSingleRule(sb, prop, rule, indent);
                    }
                }
            }
        }

        private static void EmitSingleRule(StringBuilder sb, PropertyValidation prop, ValidationRule rule, string indent)
        {
            switch (rule.Type)
            {
                case ValidationType.Length:
                    {
                        string min = rule.Min ?? "0";
                        string max = rule.Max ?? int.MaxValue.ToString(CultureInfo.InvariantCulture);
                        string message = EscapeString(rule.CustomMessage ?? $"{prop.Name} must be between {min} and {max} characters.");
                        string errorCode = EscapeString(rule.CustomErrorCode ?? "LENGTH");

                        sb.AppendLine($"{indent}if (instance.{prop.Name} != null && (instance.{prop.Name}.Length < {min} || instance.{prop.Name}.Length > {max}))");
                        sb.AppendLine($"{indent}    errors.Add(new Moongazing.OrionGuard.Core.ValidationError(\"{prop.Name}\", \"{message}\", \"{errorCode}\"));");
                    }
                    break;

                case ValidationType.Email:
                    {
                        string message = EscapeString(rule.CustomMessage ?? $"{prop.Name} must be a valid email address.");
                        string errorCode = EscapeString(rule.CustomErrorCode ?? "EMAIL");

                        // The core package's source-generated email regex carries a match timeout.
                        sb.AppendLine($"{indent}if (instance.{prop.Name} != null && !{RegexHelperName}(Moongazing.OrionGuard.Utilities.GeneratedRegexPatterns.Email(), instance.{prop.Name}))");
                        sb.AppendLine($"{indent}    errors.Add(new Moongazing.OrionGuard.Core.ValidationError(\"{prop.Name}\", \"{message}\", \"{errorCode}\"));");
                    }
                    break;

                case ValidationType.Range:
                    {
                        string min = rule.Min ?? "0";
                        string max = rule.Max ?? "0";
                        string message = EscapeString(rule.CustomMessage ?? $"{prop.Name} must be between {min} and {max}.");
                        string errorCode = EscapeString(rule.CustomErrorCode ?? "RANGE");

                        // A NaN bound fails every comparison, so the reflection-based RangeAttribute rejects
                        // every non-null value. Comparing against NaN here would do the opposite and let the
                        // value through, so the check is emitted as an outright failure instead.
                        string condition = IsNaNBound(min) || IsNaNBound(max)
                            ? (prop.IsNullable ? $"instance.{prop.Name} != null" : "true")
                            : $"{RangeComparison(prop, "<", min)} || {RangeComparison(prop, ">", max)}";

                        sb.AppendLine($"{indent}if ({condition})");
                        sb.AppendLine($"{indent}    errors.Add(new Moongazing.OrionGuard.Core.ValidationError(\"{prop.Name}\", \"{message}\", \"{errorCode}\"));");
                    }
                    break;

                case ValidationType.Positive:
                    {
                        string message = EscapeString(rule.CustomMessage ?? $"{prop.Name} must be positive.");
                        string errorCode = EscapeString(rule.CustomErrorCode ?? "POSITIVE");

                        sb.AppendLine($"{indent}if (instance.{prop.Name} <= 0)");
                        sb.AppendLine($"{indent}    errors.Add(new Moongazing.OrionGuard.Core.ValidationError(\"{prop.Name}\", \"{message}\", \"{errorCode}\"));");
                    }
                    break;

                case ValidationType.Regex:
                    {
                        string pattern = rule.Pattern ?? string.Empty;
                        string message = EscapeString(rule.CustomMessage ?? $"{prop.Name} does not match the required pattern.");
                        string errorCode = EscapeString(rule.CustomErrorCode ?? "REGEX");

                        // Escape the pattern for embedding in a verbatim string literal.
                        string escapedPattern = pattern.Replace("\"", "\"\"");

                        // RegexCache in the core package applies a match timeout, so a hostile input
                        // cannot backtrack indefinitely inside the consumer's generated validator.
                        sb.AppendLine($"{indent}if (instance.{prop.Name} != null && !{RegexHelperName}(Moongazing.OrionGuard.Core.RegexCache.GetOrCreate(@\"{escapedPattern}\"), instance.{prop.Name}))");
                        sb.AppendLine($"{indent}    errors.Add(new Moongazing.OrionGuard.Core.ValidationError(\"{prop.Name}\", \"{message}\", \"{errorCode}\"));");
                    }
                    break;
            }
        }

        /// <summary>
        /// Renders one side of a <c>[Range]</c> check with a literal of the property's type. A fractional
        /// bound was emitted as a bare double before, which does not compile against a <c>decimal</c>
        /// (CS0019) and, against a <c>float</c>, compared in double so the bound itself was rejected
        /// (0.1f is slightly greater than the double 0.1).
        /// </summary>
        private static string RangeComparison(PropertyValidation prop, string op, string bound)
        {
            string member = "instance." + prop.Name;

            // An integer bound is a valid literal for every numeric type, including custom ones such as
            // BigInteger that have no implicit conversion from double.
            if (int.TryParse(bound, NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture, out _))
            {
                return $"{member} {op} {bound}";
            }

            if (prop.NumericType == SpecialType.System_Decimal)
            {
                if (decimal.TryParse(bound, NumberStyles.Float, CultureInfo.InvariantCulture, out decimal decimalBound))
                {
                    return $"{member} {op} {decimalBound.ToString(CultureInfo.InvariantCulture)}m";
                }

                // Outside decimal's range (double.MaxValue, say) no decimal literal exists: compare in
                // double, as the reflection-based RangeAttribute does.
                string cast = prop.IsNullable ? "(double?)" : "(double)";
                return $"{cast}{member} {op} {DoubleLiteral(bound)}";
            }

            if (prop.NumericType == SpecialType.System_Single
                && float.TryParse(bound, NumberStyles.Float, CultureInfo.InvariantCulture, out float floatBound)
                && !float.IsInfinity(floatBound))
            {
                return $"{member} {op} {floatBound.ToString("R", CultureInfo.InvariantCulture)}f";
            }

            return $"{member} {op} {DoubleLiteral(bound)}";
        }

        /// <summary>
        /// Whether the generated validator, a namespace-level class in the compiling assembly, can call this
        /// getter. <c>GivesAccessTo</c> covers the same assembly and any assembly that grants it friend access.
        /// </summary>
        private static bool IsGetterAccessible(IMethodSymbol getter, IAssemblySymbol compilationAssembly)
        {
            switch (getter.DeclaredAccessibility)
            {
                case Accessibility.Public:
                    return true;
                case Accessibility.Internal:
                case Accessibility.ProtectedOrInternal:
                    return getter.ContainingAssembly is not null
                        && getter.ContainingAssembly.GivesAccessTo(compilationAssembly);
                default:
                    return false;
            }
        }

        private static bool IsNaNBound(string bound)
        {
            return double.TryParse(bound, NumberStyles.Float, CultureInfo.InvariantCulture, out double value)
                ? double.IsNaN(value)
                : bound.Trim().Equals("NaN", StringComparison.OrdinalIgnoreCase);
        }

        private static string DoubleLiteral(string bound)
        {
            double value = double.Parse(bound, NumberStyles.Float, CultureInfo.InvariantCulture);
            if (double.IsNaN(value))
            {
                return "double.NaN";
            }

            if (double.IsPositiveInfinity(value))
            {
                return "double.PositiveInfinity";
            }

            if (double.IsNegativeInfinity(value))
            {
                return "double.NegativeInfinity";
            }

            return value.ToString("R", CultureInfo.InvariantCulture) + "d";
        }

        private static string EscapeString(string value)
        {
            return value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"");
        }
    }

    // The pipeline models below are records over value types, strings and EquatableArray, so a model
    // rebuilt after an unrelated edit compares equal to the previous one and the incremental pipeline
    // reuses the cached output instead of regenerating every validator on every keystroke.

    /// <summary>
    /// Holds parsed metadata about a class/struct decorated with [GenerateValidator].
    /// </summary>
    internal sealed record ClassInfo
    {
        public ClassInfo(
            string? ns,
            string className,
            string typeFullName,
            string accessibility,
            string hintName,
            EquatableArray<PropertyValidation> properties,
            EquatableArray<UnsupportedAttribute> unsupportedAttributes,
            EquatableArray<InaccessibleMember> inaccessibleProperties)
        {
            Namespace = ns;
            ClassName = className;
            TypeFullName = typeFullName;
            Accessibility = accessibility;
            HintName = hintName;
            Properties = properties;
            UnsupportedAttributes = unsupportedAttributes;
            InaccessibleProperties = inaccessibleProperties;
        }

        public string? Namespace { get; }

        /// <summary>The simple type name; the validator is named <c>{ClassName}Validator</c>.</summary>
        public string ClassName { get; }

        /// <summary>The <c>global::</c>-qualified type name used in the generated signatures.</summary>
        public string TypeFullName { get; }

        /// <summary><c>public</c> or <c>internal</c>, whichever the validated type allows.</summary>
        public string Accessibility { get; }

        public string HintName { get; }

        public EquatableArray<PropertyValidation> Properties { get; }

        public EquatableArray<UnsupportedAttribute> UnsupportedAttributes { get; }

        public EquatableArray<InaccessibleMember> InaccessibleProperties { get; }
    }

    /// <summary>
    /// A property the generated validator cannot read, reported as OG0003.
    /// </summary>
    internal sealed record InaccessibleMember
    {
        public InaccessibleMember(string propertyName, LocationInfo location)
        {
            PropertyName = propertyName;
            Location = location;
        }

        public string PropertyName { get; }

        public LocationInfo Location { get; }
    }

    /// <summary>
    /// Holds per-property validation rule information.
    /// </summary>
    internal sealed record PropertyValidation
    {
        public PropertyValidation(
            string name, bool isString, bool isNullable, SpecialType numericType, EquatableArray<ValidationRule> rules)
        {
            Name = name;
            IsString = isString;
            IsNullable = isNullable;
            NumericType = numericType;
            Rules = rules;
        }

        public string Name { get; }
        public bool IsString { get; }
        public bool IsNullable { get; }

        /// <summary>The special type of the property, with <c>Nullable&lt;T&gt;</c> unwrapped; picks the
        /// literal suffix of <c>[Range]</c> bounds.</summary>
        public SpecialType NumericType { get; }

        public EquatableArray<ValidationRule> Rules { get; }
    }

    /// <summary>
    /// Represents a single validation rule extracted from an attribute.
    /// </summary>
    internal sealed record ValidationRule
    {
        public ValidationRule(
            ValidationType type, string? min, string? max,
            string? pattern, string? customMessage, string? customErrorCode)
        {
            Type = type;
            Min = min;
            Max = max;
            Pattern = pattern;
            CustomMessage = customMessage;
            CustomErrorCode = customErrorCode;
        }

        public ValidationType Type { get; }

        /// <summary>Lower bound, formatted with the invariant culture.</summary>
        public string? Min { get; }

        /// <summary>Upper bound, formatted with the invariant culture.</summary>
        public string? Max { get; }

        public string? Pattern { get; }
        public string? CustomMessage { get; }
        public string? CustomErrorCode { get; }
    }

    /// <summary>
    /// A validation attribute the generator cannot translate, reported as OG0002.
    /// </summary>
    internal sealed record UnsupportedAttribute
    {
        public UnsupportedAttribute(string attributeName, string propertyName, LocationInfo location)
        {
            AttributeName = attributeName;
            PropertyName = propertyName;
            Location = location;
        }

        public string AttributeName { get; }
        public string PropertyName { get; }
        public LocationInfo Location { get; }
    }

    /// <summary>
    /// A source location stored as plain values: a <see cref="Location"/> holds its syntax tree, which
    /// would keep the tree alive and break model equality across compilations.
    /// </summary>
    internal sealed record LocationInfo
    {
        private LocationInfo(string filePath, TextSpan span, LinePositionSpan lineSpan)
        {
            FilePath = filePath;
            Span = span;
            LineSpan = lineSpan;
        }

        public string FilePath { get; }
        public TextSpan Span { get; }
        public LinePositionSpan LineSpan { get; }

        public static LocationInfo From(Location location) =>
            new LocationInfo(location.SourceTree?.FilePath ?? string.Empty, location.SourceSpan, location.GetLineSpan().Span);

        public Location ToLocation() => Microsoft.CodeAnalysis.Location.Create(FilePath, Span, LineSpan);
    }

    /// <summary>
    /// The types of validation rules the generator recognizes.
    /// </summary>
    internal enum ValidationType
    {
        NotNull,
        NotEmpty,
        Length,
        Email,
        Range,
        Positive,
        Regex
    }
}
