#nullable enable

namespace Moongazing.OrionGuard.OpenApi
{
    /// <summary>
    /// The source for the <c>[OpenApiValidator]</c> marker attribute, injected into the consuming
    /// compilation by the generator (so consumers never reference an attribute assembly). The attribute
    /// names the OpenAPI document (matched against the project's AdditionalFiles by file name) and a
    /// JSON pointer to the schema within it.
    /// </summary>
    internal static class OpenApiValidatorAttributeSource
    {
        public const string FullName = "Moongazing.OrionGuard.OpenApi.OpenApiValidatorAttribute";

        public const string HintName = "OpenApiValidatorAttribute.g.cs";

        public const string Source = @"// <auto-generated/>
#nullable enable

namespace Moongazing.OrionGuard.OpenApi
{
    /// <summary>
    /// Marks a partial class as an OpenAPI-derived validator. At compile time the OrionGuard OpenAPI
    /// generator reads the referenced schema from the named OpenAPI document (supplied as an
    /// AdditionalFile) and emits the validator body implementing
    /// <c>Moongazing.OrionGuard.DependencyInjection.IValidator&lt;T&gt;</c>.
    /// </summary>
    /// <example>
    /// <code>
    /// [OpenApiValidator(""openapi.json"", ""#/components/schemas/Customer"")]
    /// public partial class CustomerValidator { }
    /// </code>
    /// </example>
    [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class OpenApiValidatorAttribute : System.Attribute
    {
        /// <summary>
        /// Creates the marker.
        /// </summary>
        /// <param name=""documentPath"">
        /// The OpenAPI document, matched against the project's AdditionalFiles by file name (a full
        /// relative path also matches). For example <c>openapi.json</c>.
        /// </param>
        /// <param name=""schemaPointer"">
        /// A same-document JSON pointer to the schema, for example
        /// <c>#/components/schemas/Customer</c>.
        /// </param>
        public OpenApiValidatorAttribute(string documentPath, string schemaPointer)
        {
            DocumentPath = documentPath;
            SchemaPointer = schemaPointer;
        }

        /// <summary>The OpenAPI document file name (matched against AdditionalFiles).</summary>
        public string DocumentPath { get; }

        /// <summary>The JSON pointer to the schema within the document.</summary>
        public string SchemaPointer { get; }
    }
}
";
    }
}
