namespace Moongazing.OrionGuard.SchemaExport.Tests;

public sealed class TypeScriptExporterTests
{
    [Fact]
    public void Export_PlainType_DeclaresTheInterfaceWithoutAnyRuleComments()
    {
        var expected = """
            // Generated by OrionGuard.SchemaExport from Moongazing.OrionGuard.SchemaExport.Tests.PlainProfile.
            // Types only: the constraints below are documented here, not enforced here.

            export interface PlainProfile {
              displayName?: string;
              visits?: number;
            }

            """;

        Assert.Equal(Normalize(expected), TypeScriptExporter.Export<PlainProfile>());
    }

    [Fact]
    public void Export_EverySupportedConstraint_BecomesADocCommentOnItsMember()
    {
        var expected = """
            // Generated by OrionGuard.SchemaExport from Moongazing.OrionGuard.SchemaExport.Tests.ConstrainedRequest.
            // Types only: the constraints below are documented here, not enforced here.

            export interface ConstrainedRequest {
              /** required */
              id: string;
              /** required; not blank */
              nickname: string;
              /** 3 to 50 characters */
              slug?: string;
              /** pattern: ^[a-z0-9-]+$ */
              handle?: string;
              /** format: email */
              email?: string;
              /** between 13 and 120 */
              age?: number;
              /** greater than 0 */
              budget?: number;
              /** format: uri */
              website?: string | null;
            }

            """;

        Assert.Equal(Normalize(expected), TypeScriptExporter.Export<ConstrainedRequest>());
    }

    [Fact]
    public void Export_NestedType_DeclaresAnInterfaceForItAndReferencesItByName()
    {
        var expected = """
            // Generated by OrionGuard.SchemaExport from Moongazing.OrionGuard.SchemaExport.Tests.Order.
            // Types only: the constraints below are documented here, not enforced here.

            export interface Order {
              /** required */
              shipTo: Address;
              billTo?: Address | null;
            }

            export interface Address {
              /** required; not blank */
              city: string;
            }

            """;

        Assert.Equal(Normalize(expected), TypeScriptExporter.Export<Order>());
    }

    [Fact]
    public void Export_Collections_BecomeArrayTypes()
    {
        var declaration = TypeScriptExporter.Export<Basket>();

        Assert.Contains("  /** required; at least 1 item */\n  lines: OrderLine[];\n", declaration, StringComparison.Ordinal);
        Assert.Contains("  tags?: string[];\n", declaration, StringComparison.Ordinal);
        Assert.Contains("export interface OrderLine {", declaration, StringComparison.Ordinal);
    }

    [Fact]
    public void Export_NullableMembers_AreOptionalAndAcceptNull()
    {
        var declaration = TypeScriptExporter.Export<Contact>();

        Assert.Contains("  nickname?: string | null;\n", declaration, StringComparison.Ordinal);
        Assert.Contains("  age?: number | null;\n", declaration, StringComparison.Ordinal);
    }

    [Fact]
    public void Export_NotNullMember_IsNotOptionalAndDoesNotAcceptNull()
    {
        var declaration = TypeScriptExporter.Export<Contact>();

        Assert.Contains("  email: string;\n", declaration, StringComparison.Ordinal);
    }

    [Fact]
    public void Export_Enum_BecomesAUnionOfTheMemberNames()
    {
        var declaration = TypeScriptExporter.Export<Shipment>();

        Assert.Contains("  status?: 'Pending' | 'Shipped' | 'Delivered';\n", declaration, StringComparison.Ordinal);
        Assert.Contains("  previousStatus?: 'Pending' | 'Shipped' | 'Delivered' | null;\n", declaration, StringComparison.Ordinal);
    }

    [Fact]
    public void Export_RuleTheDeclarationCannotExpress_SaysSoAboveTheMember()
    {
        var expected = """
            // Generated by OrionGuard.SchemaExport from Moongazing.OrionGuard.SchemaExport.Tests.PasswordChange.
            // Types only: the constraints below are documented here, not enforced here.

            export interface PasswordChange {
              /** required; 8 to 64 characters */
              password: string;
              // not enforced here: MatchesPasswordAttribute
              confirmation?: string;
              // not enforced here: EvenNumberAttribute
              slots?: number;
            }

            """;

        Assert.Equal(Normalize(expected), TypeScriptExporter.Export<PasswordChange>());
    }

    [Fact]
    public void Export_SerializedNameThatIsNotAnIdentifier_IsQuotedSoTheDeclarationParses()
    {
        var declaration = TypeScriptExporter.Export<WireNames>();

        Assert.Contains("  \"first-name\"?: string;\n", declaration, StringComparison.Ordinal);
        Assert.Contains("  \"2fa\"?: boolean;\n", declaration, StringComparison.Ordinal);
    }

    [Fact]
    public void Export_SerializedNameHoldingAQuote_EscapesItInsideTheQuotedName()
    {
        var declaration = TypeScriptExporter.Export<WireNames>();

        Assert.Contains("  \"say \\\"hi\\\"\"?: string | null;\n", declaration, StringComparison.Ordinal);
    }

    [Fact]
    public void Export_SerializedNameThatIsAnIdentifier_StaysUnquoted()
    {
        var declaration = TypeScriptExporter.Export<WireNames>();

        Assert.Contains("  plain?: string;\n", declaration, StringComparison.Ordinal);
    }

    [Fact]
    public void Export_NotEmptyOnAString_SaysNotBlankRatherThanAMinimumLength()
    {
        var declaration = TypeScriptExporter.Export<Address>();

        Assert.Contains("  /** required; not blank */\n  city: string;\n", declaration, StringComparison.Ordinal);
        Assert.DoesNotContain("at least 1 character", declaration, StringComparison.Ordinal);
    }

    [Fact]
    public void Export_PatternThatIsNotEcmaScript_IsReportedInsteadOfDocumented()
    {
        var declaration = TypeScriptExporter.Export<PatternRules>();

        Assert.Contains("  /** pattern: ^[a-z]+$ */\n  portable?: string;\n", declaration, StringComparison.Ordinal);
        Assert.Contains("  // not enforced here: RegexAttribute\n  inlineOptions?: string;\n", declaration, StringComparison.Ordinal);
        Assert.DoesNotContain("(?i)", declaration, StringComparison.Ordinal);
        Assert.DoesNotContain(@"\Aabc\z", declaration, StringComparison.Ordinal);
    }

    [Fact]
    public void Export_NullableCollectionElement_AcceptsNullInsideTheArray()
    {
        var declaration = TypeScriptExporter.Export<Roster>();

        Assert.Contains("  nicknames?: (string | null)[];\n", declaration, StringComparison.Ordinal);
        Assert.Contains("  names?: string[];\n", declaration, StringComparison.Ordinal);
        Assert.Contains("  aliases?: (string | null)[];\n", declaration, StringComparison.Ordinal);
        Assert.Contains("  scores?: (number | null)[];\n", declaration, StringComparison.Ordinal);
    }

    [Fact]
    public void Export_NestedCollection_ReachesTheInterfaceAtTheBottomOfIt()
    {
        var declaration = TypeScriptExporter.Export<Warehouse>();

        Assert.Contains("  shelves?: Address[][];\n", declaration, StringComparison.Ordinal);
        Assert.Contains("export interface Address {", declaration, StringComparison.Ordinal);
        Assert.DoesNotContain("unknown", declaration, StringComparison.Ordinal);
    }

    [Fact]
    public void Export_ByteArray_IsAStringNotAnArrayOfNumbers()
    {
        var declaration = TypeScriptExporter.Export<Upload>();

        Assert.Contains("  content?: string;\n", declaration, StringComparison.Ordinal);
        Assert.Contains("  thumbnail?: string | null;\n", declaration, StringComparison.Ordinal);
        Assert.DoesNotContain("number[]", declaration, StringComparison.Ordinal);
    }

    // The exporter always writes "\n" so the artifact is byte-identical on every platform.
    private static string Normalize(string declaration) => declaration.Replace("\r\n", "\n");
}
