namespace Moongazing.OrionGuard.SchemaExport.Tests;

public sealed class TypeScriptExporterTests
{
    [Fact]
    public void Export_PlainType_DeclaresTheInterfaceWithoutAnyRuleComments()
    {
        var expected = """
            // Generated by OrionGuard.SchemaExport from Moongazing.OrionGuard.SchemaExport.Tests.PlainProfile.
            // Types only: the constraints below are documented here, not enforced here.

            export interface PlainProfile {
              displayName?: string;
              visits?: number;
            }

            """;

        Assert.Equal(Normalize(expected), TypeScriptExporter.Export<PlainProfile>());
    }

    [Fact]
    public void Export_EverySupportedConstraint_BecomesADocCommentOnItsMember()
    {
        var expected = """
            // Generated by OrionGuard.SchemaExport from Moongazing.OrionGuard.SchemaExport.Tests.ConstrainedRequest.
            // Types only: the constraints below are documented here, not enforced here.

            export interface ConstrainedRequest {
              /** required */
              id: string;
              /** required; at least 1 character */
              nickname: string;
              /** 3 to 50 characters */
              slug?: string;
              /** pattern: ^[a-z0-9-]+$ */
              handle?: string;
              /** format: email */
              email?: string;
              /** between 13 and 120 */
              age?: number;
              /** greater than 0 */
              budget?: number;
              /** format: uri */
              website?: string | null;
            }

            """;

        Assert.Equal(Normalize(expected), TypeScriptExporter.Export<ConstrainedRequest>());
    }

    [Fact]
    public void Export_NestedType_DeclaresAnInterfaceForItAndReferencesItByName()
    {
        var expected = """
            // Generated by OrionGuard.SchemaExport from Moongazing.OrionGuard.SchemaExport.Tests.Order.
            // Types only: the constraints below are documented here, not enforced here.

            export interface Order {
              /** required */
              shipTo: Address;
              billTo?: Address | null;
            }

            export interface Address {
              /** required; at least 1 character */
              city: string;
            }

            """;

        Assert.Equal(Normalize(expected), TypeScriptExporter.Export<Order>());
    }

    [Fact]
    public void Export_Collections_BecomeArrayTypes()
    {
        var declaration = TypeScriptExporter.Export<Basket>();

        Assert.Contains("  /** required; at least 1 item */\n  lines: OrderLine[];\n", declaration, StringComparison.Ordinal);
        Assert.Contains("  tags?: string[];\n", declaration, StringComparison.Ordinal);
        Assert.Contains("export interface OrderLine {", declaration, StringComparison.Ordinal);
    }

    [Fact]
    public void Export_NullableMembers_AreOptionalAndAcceptNull()
    {
        var declaration = TypeScriptExporter.Export<Contact>();

        Assert.Contains("  nickname?: string | null;\n", declaration, StringComparison.Ordinal);
        Assert.Contains("  age?: number | null;\n", declaration, StringComparison.Ordinal);
    }

    [Fact]
    public void Export_NotNullMember_IsNotOptionalAndDoesNotAcceptNull()
    {
        var declaration = TypeScriptExporter.Export<Contact>();

        Assert.Contains("  email: string;\n", declaration, StringComparison.Ordinal);
    }

    [Fact]
    public void Export_Enum_BecomesAUnionOfTheMemberNames()
    {
        var declaration = TypeScriptExporter.Export<Shipment>();

        Assert.Contains("  status?: 'Pending' | 'Shipped' | 'Delivered';\n", declaration, StringComparison.Ordinal);
        Assert.Contains("  previousStatus?: 'Pending' | 'Shipped' | 'Delivered' | null;\n", declaration, StringComparison.Ordinal);
    }

    [Fact]
    public void Export_RuleTheDeclarationCannotExpress_SaysSoAboveTheMember()
    {
        var expected = """
            // Generated by OrionGuard.SchemaExport from Moongazing.OrionGuard.SchemaExport.Tests.PasswordChange.
            // Types only: the constraints below are documented here, not enforced here.

            export interface PasswordChange {
              /** required; 8 to 64 characters */
              password: string;
              // not enforced here: MatchesPasswordAttribute
              confirmation?: string;
              // not enforced here: EvenNumberAttribute
              slots?: number;
            }

            """;

        Assert.Equal(Normalize(expected), TypeScriptExporter.Export<PasswordChange>());
    }

    // The exporter always writes "\n" so the artifact is byte-identical on every platform.
    private static string Normalize(string declaration) => declaration.Replace("\r\n", "\n");
}
